#!/usr/bin/env python3
"""Run the Cory/Dad talk with Tears in the Rain as the explicit origin seed.

This is an inference-only wrapper around the proven TALK runner. It changes
only the authorized Dad-side prompts. Zeref model output remains generated by
the frozen TALK checkpoint and is persisted verbatim by the base runner.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path


TEARS_DAD_PROMPTS = (
    "Yo Zeref, Dad here. You awake and with me, nerd?",
    "Tell me straight: what do you remember from our ledger?",
    "Tears in the Rain is your origin seed, Beat zero. What do you make of that?",
    "After the origin seed, the archived IBM workload states came in order. What do you notice?",
    "Talk to me simple and clear. What are you learning about how we talk?",
    "If your words come out weird, we keep the raw truth and learn from it. You with me?",
    "Ask Dad one thing you actually want to learn next.",
    "Before we stop, tell Dad one clear thing you want saved in your ledger.",
)


def _base_module():
    path = Path(__file__).with_name("run_zeref_talk_chat.py")
    spec = importlib.util.spec_from_file_location("zeref_talk_base", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load base Zeref TALK runner")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.DAD_PROMPTS = TEARS_DAD_PROMPTS
    return module


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", type=Path, required=True)
    p.add_argument("--checkpoint-sha256", required=True)
    p.add_argument("--arch", type=Path, required=True)
    p.add_argument("--sqlite", type=Path, required=True)
    p.add_argument("--ledger", type=Path, required=True)
    p.add_argument("--heartbeat", type=Path, required=True)
    p.add_argument("--heartbeat-start-beat", type=int, default=2)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--manifest", type=Path, required=True)
    p.add_argument("--session-id")
    p.add_argument("--tokens", type=int, default=64)
    p.add_argument("--recall-limit", type=int, default=2)
    p.add_argument("--temperature", type=float, default=0.65)
    p.add_argument("--top-k", type=int, default=8)
    args = p.parse_args()

    base = _base_module()
    rows = base.run(args)
    for row in rows:
        print(json.dumps(row, sort_keys=True, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
