"""Static COSMIC.CYPHER browser surface.

Device handles stay browser-local. JavaScript sends only explicit bounded feature
observations to the loopback controller unless a future capability says otherwise.
"""
from __future__ import annotations

import json


def render_cosmic_ui(session_token: str = "local-test-session") -> str:
    return _HTML.replace("__BEAST_SESSION__", json.dumps(session_token))


_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Beast Box · COSMIC.CYPHER</title>
<style>

:root{
 color-scheme:dark;--bg:#04070c;--near-black:#080d14;--panel:#0c1520;--panel2:#111e2c;
 --slate:#253647;--line:#2c3e4e;--text:#edf3f5;--muted:#a3b2bf;
 --cyan:#88dfe3;--gold:#ebcc80;--green:#a5e2ba;--red:#ff929b;--violet:#b9a3e3;
 --s1:4px;--s2:8px;--s3:12px;--s4:16px;--s6:24px;--s8:32px;--s12:48px;
 --mono:ui-monospace,SFMono-Regular,Consolas,monospace;--radius:8px;
}
*{box-sizing:border-box}html{background:var(--bg)}
body{margin:0;min-height:100vh;color:var(--text);font:14px/1.6 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:radial-gradient(ellipse at 82% 5%,#12303955,transparent 44%),var(--bg)}
button,input,select,textarea{font:inherit}button,a,input,textarea,select,summary{-webkit-tap-highlight-color:transparent}
button{cursor:pointer;min-height:40px;border:1px solid var(--line);border-radius:5px;padding:10px 14px;color:var(--text);background:#142330;font-size:11px;font-weight:650;letter-spacing:.05em;transition:background .15s,border-color .15s}
button:hover{background:#1c3440;border-color:#669098}button:disabled{opacity:.45;cursor:not-allowed}
button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,summary:focus-visible{outline:2px solid var(--cyan);outline-offset:4px}
button.primary{background:#bce6d7;color:#102a26;border-color:#bce6d7}button.primary:hover{background:#d3f3e5}
button.danger{border-color:#824650;background:#2a171f;color:#ffd6da}button.danger:hover{background:#42202a}
a{color:var(--cyan)}p{margin:12px 0}h1,h2,h3{line-height:1.15}h1{font-size:clamp(24px,2.8vw,34px);font-weight:550;letter-spacing:-.035em;margin:6px 0}
h2{font-size:25px;font-weight:500;letter-spacing:-.025em;margin:12px 0}h3{font-size:18px;font-weight:550;margin:8px 0}
.app{display:grid;grid-template-columns:214px minmax(0,1fr);min-height:100vh}
.rail{position:sticky;top:0;height:100vh;overflow:auto;padding:28px 16px 20px;border-right:1px solid #23323e;background:#070d14}
.brand{display:flex;gap:10px;align-items:center;padding:0 4px 24px;font-size:15px;font-weight:750;letter-spacing:.12em}.brand small{display:block;font-size:9px;font-weight:500;letter-spacing:.22em;color:var(--muted);margin-top:3px}.brand svg{width:36px;flex-shrink:0}
.nav-group{display:block;color:#8098a7;font:9px var(--mono);letter-spacing:.16em;margin:19px 10px 7px}.nav button{width:100%;text-align:left;display:block;margin:3px 0;background:transparent;border-color:transparent;color:#afbec9;font-size:10px;letter-spacing:.09em;padding:9px 10px;min-height:36px}
.nav button:before{content:'';display:inline-block;width:5px;height:5px;border:1px solid #647887;margin-right:12px;transform:rotate(45deg)}.nav button.active{color:#c6f1ed;background:#123039;border-color:#28454a}.nav button.active:before{background:var(--cyan);border-color:var(--cyan)}
.rail-note{margin:24px 10px 0;padding-top:16px;border-top:1px solid var(--line);font:9px/1.8 var(--mono);color:var(--muted)}
.main{position:relative;min-width:0;width:100%;max-width:1540px;margin:0 auto;padding:28px 36px}
.top{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:24px}.eyebrow{font:10px var(--mono);letter-spacing:.16em;color:var(--cyan)}
.statusbar{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end;max-width:530px}.pill{display:inline-flex;align-items:center;border:1px solid var(--line);border-radius:4px;padding:5px 8px;font:10px/1.45 var(--mono);color:#b4c6ce;background:#0b141d;overflow-wrap:anywhere;min-width:0}
.privacy{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:12px 16px;margin-bottom:16px;border:1px solid #47323a;border-radius:var(--radius);background:#151219}.privacy b{font-size:10px;letter-spacing:.1em;color:#ecb6bc}.privacy small{font-size:11px;color:#bbaeb5}.privacy button{flex-shrink:0;min-height:34px;padding:8px 12px;font-size:10px}
.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:16px}.card{grid-column:span 4;min-width:0;padding:24px;border:1px solid var(--line);border-radius:var(--radius);background:linear-gradient(145deg,#101b27,#0b131c)}.wide{grid-column:span 8}.half{grid-column:span 6}.full{grid-column:1/-1}
.label{text-transform:uppercase;font:10px/1.5 var(--mono);letter-spacing:.11em;color:#afc2cb}.value{font-size:25px;line-height:1.3;font-weight:550;letter-spacing:-.025em;margin-top:10px;overflow-wrap:anywhere}.sub{font-size:12px;color:var(--muted);margin-top:7px}.mono{font-family:var(--mono);font-size:11px;overflow-wrap:anywhere}.ok{color:var(--green)}.live{color:#c8f2d9!important;border-color:#547b66!important;background:#152f25!important}
.warning{padding:12px 16px;border-left:2px solid var(--gold);background:#25201480;color:#f4dfaf;font-size:12px;border-radius:0 5px 5px 0}.notice{position:sticky;top:8px;z-index:5;padding:12px 16px;border:1px solid #446557;background:#112a24;border-radius:6px;margin-bottom:16px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.notice.error{border-color:#ae5260;background:#321922;color:#ffdce2}
#handoff{margin-bottom:16px;animation:clock-in .7s ease-out}@keyframes clock-in{from{opacity:.35;transform:translateY(4px)}to{opacity:1;transform:none}}
.observatory{position:relative;display:grid;grid-template-columns:1.03fr 1fr;gap:24px;align-items:center;padding:40px 32px;margin-bottom:16px;border:1px solid #304a51;border-radius:var(--radius);overflow:hidden;background:radial-gradient(ellipse at 80% 40%,#164c4824,transparent 60%),linear-gradient(#25434a15 1px,transparent 1px),linear-gradient(90deg,#25434a15 1px,transparent 1px),#0a141b;background-size:auto,32px 32px,32px 32px,auto}
.observatory h2{font-size:clamp(36px,3.6vw,54px);letter-spacing:-.055em;line-height:1.08;font-weight:450;margin:22px 0}.observatory h2 em{font-style:normal;color:#b9e6d5}.observatory p{max-width:360px;font-size:13px;color:#b7c7ce;margin-bottom:24px}.observatory .eyebrow{color:var(--gold)}.hero-actions{display:flex;flex-wrap:wrap;gap:8px}.hero-caption{margin-top:24px;font:9px var(--mono);letter-spacing:.1em;color:#95aeba}
.system-map{position:relative;min-height:320px;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:76px 100px 100px;gap:12px 24px;align-items:center;text-align:center;padding:8px;isolation:isolate}.system-map:before{content:'';position:absolute;z-index:-1;inset:27px 26px 32px;border:1px solid #56827d55;border-radius:50%;transform:rotate(-22deg)}.system-map:after{content:'';position:absolute;z-index:-1;inset:48px 60px;border:1px dashed #86a79038;border-radius:50%;transform:rotate(40deg)}.map-node{padding:10px 12px;border:1px solid #355052;background:#0a1820ee;border-radius:6px;min-width:0}.map-node span{display:block;color:#9bb7bc;font:9px var(--mono);letter-spacing:.1em}.map-node strong{display:block;margin-top:4px;font:11px var(--mono);color:#d2e9e5;overflow-wrap:anywhere}.map-brain{grid-column:1/-1;justify-self:center;min-width:160px;max-width:270px;border-color:#7b7450}.map-brain span{color:var(--gold)}.map-core{grid-column:1/-1;justify-self:center;min-width:170px;position:relative;background:#122f2c;border-color:#628a74}.map-core:before{content:'';width:7px;height:7px;border-radius:50%;display:inline-block;background:var(--green);margin-bottom:4px}.map-caption{position:absolute;bottom:-2px;width:100%;font:9px var(--mono);color:#a3bcb4}
.orbit-metrics .card{grid-column:span 3;padding:20px}.orbit-metrics .value{font:16px/1.4 var(--mono);margin-top:12px}.orbit-metrics .metric-number{font:32px/1.2 var(--mono);color:var(--green)}.orbit-metrics .full{grid-column:1/-1}.quickpaths{display:flex;gap:16px;align-items:center;justify-content:space-between;flex-wrap:wrap}.quickpaths h3{margin:0}.quickpaths p{margin:4px 0;color:var(--muted);font-size:12px}
.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;justify-content:space-between}.toolbar h2{margin-right:auto}.toolbar button{margin:0}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:end}.card label{display:block;font-size:12px;color:#beccd4;margin:16px 0 8px}.card label input,.card label select,.card label textarea{margin-top:7px}input,select,textarea{width:100%;padding:11px 12px;color:var(--text);background:#080f17;border:1px solid var(--line);border-radius:5px;min-width:0}input[type=checkbox],input[type=radio]{width:auto;accent-color:#91d5c5}textarea{resize:vertical}::placeholder{color:#7f95a6}
.chatlog{height:min(50vh,480px);min-height:280px;overflow:auto;padding:16px;border:1px solid #233745;border-radius:6px;background:#080f17;margin-top:20px}.empty{padding:48px 16px;text-align:center;color:#becfd5}.empty strong{font-size:20px;font-weight:500;display:block;margin-bottom:10px}.msg{max-width:88%;margin:12px 0;padding:16px;background:#11222c;border:1px solid #2a3f49;border-radius:6px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}.msg.user{margin-left:auto;background:#172622;border-color:#3b5547}.msg .sub{padding-top:12px;border-top:1px solid #335052;font:10px var(--mono);white-space:normal}.composer{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;margin-top:12px}.composer textarea{min-height:80px}.context-picker label{font-size:12px;margin:8px 0}.context-picker input{width:auto}
.brain-slots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:24px 0}.brain-slot{min-height:152px;text-align:left;position:relative;padding:20px;background:#0a141e;border-color:#304352;letter-spacing:normal}.brain-slot .slot-symbol{display:block;color:#adc5cb;font-size:24px;line-height:1}.brain-slot strong{display:block;font-size:16px;font-weight:550;margin:16px 0 8px}.brain-slot small{display:block;color:var(--muted);font:10px/1.6 var(--mono)}.brain-slot[aria-pressed=true]{background:#1a2927;border-color:#b6cfb1}.brain-slot[aria-pressed=true] .slot-symbol{color:var(--gold)}.slot-state{position:absolute;top:20px;right:16px;font:8px var(--mono);letter-spacing:.12em;color:var(--gold)}.boundary-strip{display:flex;gap:16px;flex-wrap:wrap;padding:16px 0;border-top:1px solid var(--line);margin-top:24px}.boundary-strip span{font:10px var(--mono);color:#b1c9c6}.boundary-strip b{color:var(--green);font-weight:500}
.records{overflow-wrap:anywhere}.record{padding:20px 0;border-bottom:1px solid var(--line)}.record:last-child{border-bottom:0}.record p{white-space:pre-wrap;font-size:13px}.meta{font:10px/1.7 var(--mono);color:#a8bdc5;margin:7px 0;overflow-wrap:anywhere}.memory-record{position:relative;padding:20px 20px 20px 32px;margin-left:8px;border-left:1px solid #4b735f;border-bottom:1px solid #233c36;background:linear-gradient(90deg,#16332855,transparent)}.memory-record:before{content:'';position:absolute;left:-4px;top:27px;width:7px;height:7px;border-radius:50%;background:var(--green)}.memory-record strong{font-weight:550}.memory-date{font:10px var(--mono);color:var(--green);letter-spacing:.1em;margin:24px 0 14px}.memory-constellation{display:flex;align-items:center;gap:7px;flex-wrap:wrap;padding:16px 0}.memory-node{min-height:24px;width:24px;padding:0;border:1px solid #6d9477;background:#162e23;border-radius:50%;font-size:8px;color:#d4eedd}.memory-node:hover{background:#38634a}.memory-constellation .line{width:16px;height:1px;background:#476c53}.memory-controls{display:grid;grid-template-columns:1fr 180px;gap:16px;margin:16px 0}.memory-controls label{margin:0}
.trace-node{position:relative;margin:0 0 0 8px;padding:18px 0 18px 24px;border-left:1px solid #476b77;background:linear-gradient(90deg,#18324144,transparent);border-bottom:1px solid #203241}.trace-node:before{content:'';position:absolute;left:-4px;top:25px;width:7px;height:7px;border-radius:50%;background:var(--cyan)}.trace-node summary{font:12px/1.7 var(--mono);padding-right:12px}.trace-summary{padding:16px 0}.trace-stages{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.trace-stage{font:9px/1.5 var(--mono);padding:5px 8px;border:1px solid #385766;background:#123040;color:#c6e2ee;border-radius:3px}.trace-stage.inactive{background:transparent;border-style:dashed;border-color:#34434c;color:#90a0ab}.trace-stage.checkpoint{border-color:#677c49;color:var(--green);background:#1f2d1b}.trace-node pre{margin-right:16px}.session-events{margin-top:24px}.session-events h3{font-size:16px}.trace-node.session{border-left-color:#946d58}.trace-node.session:before{background:var(--gold)}
.scope-options{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:20px 0}.scope-choice{padding:14px;text-align:left;background:#0a151d;letter-spacing:normal;min-height:100px}.scope-choice strong{font-size:10px;display:block;letter-spacing:.06em;margin-bottom:7px}.scope-choice small{color:#a8bdc5;font-size:11px;font-weight:400;line-height:1.5;display:block}.scope-choice[aria-pressed=true]{border-color:var(--cyan);background:#173039}.scope-choice[data-scope=persistent_memory][aria-pressed=true]{border-color:var(--gold);background:#30291c}
.authority-row{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:20px 0;border-bottom:1px solid #2d3f48}.authority-row:last-child{border:0}.authority-row strong{display:block;font:12px var(--mono);color:#d3e2e6}.authority-row .gate-dot{display:inline-block;width:7px;height:7px;border:1px solid #8a9ba4;border-radius:50%;margin-right:10px}.authority-row.granted .gate-dot{background:var(--red);border-color:var(--red)}.authority-row button{min-width:85px}.authority-meta{font:9px var(--mono);letter-spacing:.06em;color:#b6a8ae}.authority-manifest{border-left:2px solid var(--gold);padding-left:20px;margin:24px 0;font-size:clamp(17px,2vw,24px);line-height:1.45;letter-spacing:-.02em}.authority-summary{display:flex;gap:8px;flex-wrap:wrap}
.file-tree{max-height:430px;overflow:auto;margin-top:16px}.file-tree button{width:100%;display:block;min-height:32px;padding:6px 8px;border:0;border-radius:3px;text-align:left;background:transparent;font:11px/1.7 var(--mono);overflow-wrap:anywhere}.file-tree button:hover,.file-tree button.selected{background:#1c333f;color:#d0eeea}.file-tree button:before{content:'›';color:#8acdc4;margin-right:10px}.editor{min-height:300px;font:12px/1.75 var(--mono);tab-size:4}.workspace-status{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.diff-view{font:11px/1.6 var(--mono);max-height:400px;overflow:auto;margin:12px 0;border:1px solid var(--line);background:#071018;border-radius:5px;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere}.diff-line{display:block;min-height:1.6em}.diff-line.added{color:#b5ebc8;background:#193529}.diff-line.removed{color:#ffd2d7;background:#351e26}.search-hits button{display:block;width:100%;text-align:left;margin:8px 0;font:11px/1.6 var(--mono);overflow-wrap:anywhere}.search-hits small{display:block;color:var(--muted)}
.facts{display:grid;grid-template-columns:200px minmax(0,1fr);gap:12px 24px;margin:24px 0}.facts dt{font:10px/1.8 var(--mono);color:var(--muted)}.facts dd{margin:0;font:11px/1.8 var(--mono);overflow-wrap:anywhere}.capsule-mark{font:10px var(--mono);color:var(--gold);letter-spacing:.16em}.trust-cells{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.trust-cell{padding:16px;border:1px solid var(--line);border-radius:5px;background:#09131c;overflow-wrap:anywhere}.trust-cell b{font:10px/1.6 var(--mono);color:var(--green);display:block;margin:8px 0}.trust-cell:last-child b{color:var(--gold)}.trust-cell small{color:var(--muted);font-size:11px}
pre{max-height:470px;overflow:auto;margin:12px 0 0;padding:16px;border:1px solid var(--line);border-radius:5px;background:#070f18;white-space:pre-wrap;word-break:break-word;font:11px/1.7 var(--mono)}summary{cursor:pointer;overflow-wrap:anywhere;color:#b7cbd2;font-size:12px}details{margin-top:12px}details[open]>summary{color:var(--cyan);margin-bottom:12px}
video.camera{display:block;width:100%;max-height:390px;border:1px solid var(--line);border-radius:6px;background:#000;margin:20px 0}canvas.scope{width:100%;height:140px;border:1px solid var(--line);border-radius:5px;background:#050b12;margin:20px 0}
.demo-guide{padding:20px 24px;border:1px solid #817448;border-radius:6px;background:#201e14;margin-bottom:16px}.demo-guide h3{font-size:17px;color:#f1dfb4}.demo-guide p{font-size:12px;color:#d1c7ac;margin:8px 0}.demo-progress{font:10px var(--mono);color:var(--gold)}.demo-guide .toolbar{align-items:flex-start}.demo-guide button{border-color:#756841}.demo-guide .demo-receipt{font:10px var(--mono);color:var(--green);overflow-wrap:anywhere}
footer{display:flex;gap:24px;justify-content:space-between;border-top:1px solid #223540;padding-top:20px;margin-top:32px;font:9px/1.7 var(--mono);letter-spacing:.1em;color:#9db0bd}.skip{position:fixed;top:-100px;left:16px;z-index:20;background:#c1ebdf;color:#112c27;padding:12px}.skip:focus{top:12px}.hidden{display:none!important}
@media(max-width:1200px){.app{grid-template-columns:188px minmax(0,1fr)}.main{padding:24px}.rail{padding:24px 12px}.brand{font-size:13px}.brand svg{width:28px}.observatory{padding:32px 24px;gap:16px}.system-map{padding:0;gap:12px}.map-node{padding:10px 8px}.orbit-metrics .card{grid-column:span 6}.orbit-metrics .full{grid-column:1/-1}.top{align-items:flex-start}.statusbar{max-width:340px}.card{padding:20px}}
@media(max-width:920px){.app{grid-template-columns:1fr}.rail{position:relative;height:auto;padding:10px 16px;border:0;border-bottom:1px solid var(--line)}.brand,.rail-note,.nav-group{display:none}.nav{display:flex;gap:4px;overflow:auto}.nav button{width:auto;white-space:nowrap;flex-shrink:0}.main{padding:24px}.card,.wide,.half{grid-column:1/-1}.top{align-items:flex-start}.observatory h2{font-size:40px}.facts{grid-template-columns:170px minmax(0,1fr)}}
@media(max-width:600px){.main{padding:16px}.top{flex-direction:column;gap:12px;margin-bottom:16px}.statusbar{justify-content:flex-start;max-width:none}.privacy{flex-direction:column;align-items:flex-start;gap:8px}.observatory{grid-template-columns:1fr;padding:28px 20px}.observatory h2{font-size:42px}.observatory p{font-size:12px}.system-map{min-height:290px;margin-top:8px;grid-template-rows:70px 85px 85px}.hero-caption{font-size:8px}.orbit-metrics .card{padding:16px}.orbit-metrics .value{font-size:12px}.orbit-metrics .metric-number{font-size:26px}.orbit-metrics .label{font-size:9px}.grid{gap:12px}.card{padding:18px}.brain-slots{grid-template-columns:1fr;gap:8px}.brain-slot{min-height:105px;padding:16px}.brain-slot strong{margin:8px 0}.brain-slot .slot-symbol{font-size:18px}.fields,.composer,.memory-controls{grid-template-columns:1fr}.facts{grid-template-columns:1fr;gap:5px}.facts dd{margin-bottom:12px}.trust-cells{grid-template-columns:1fr;gap:8px}.trust-cell{padding:12px}.authority-row{gap:12px}.authority-row strong{font-size:10px}.authority-row button{min-width:70px;padding:8px}.authority-meta{font-size:8px;line-height:1.7}.msg{max-width:95%}.memory-record{padding:16px 8px 16px 20px}.trace-node{padding-left:16px}.scope-choice{padding:12px}footer{flex-direction:column;gap:8px}.demo-guide{padding:16px}.hero-actions button{padding:10px 12px;font-size:10px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}

</style></head><body><a class="skip" href="#main">Skip to workstation</a><div class="app"><aside class="rail"><div class="brand"><svg viewBox="0 0 48 48" fill="none" aria-hidden="true"><path d="M16 8H8V40H40V8H32" stroke="#a9c7c3" stroke-width="2"/><ellipse cx="24" cy="25" rx="18" ry="8" transform="rotate(-35 24 25)" stroke="#86dadd"/><path d="M24 14V34M18 25H30" stroke="#a8daba"/><circle cx="24" cy="8" r="4" fill="#ebcc80"/><circle cx="24" cy="25" r="3" fill="#a8daba"/></svg><div>BEAST BOX<small>COSMIC.CYPHER</small></div></div><nav class="nav" id="nav" aria-label="Workstation">
<span class="nav-group">YOUR CONTINUITY</span><button class="active" data-view="orbit">ORBIT</button><button data-view="brain">BRAIN</button><button data-view="bay">BRAIN BAY</button><span class="nav-group">YOUR OBSERVATORY</span><button data-view="vision">VISION</button><button data-view="listen">LISTEN</button><button data-view="voice">VOICE</button><button data-view="reality">REALITY</button><span class="nav-group">YOUR WORK</span><button data-view="memory">MEMORY VAULT</button><button data-view="trace">SYNAPSE TRACE</button><button data-view="files">FILES</button><button data-view="workspace">WORKSPACE</button><span class="nav-group">YOUR BOUNDARIES</span><button data-view="qbay">Q-BAY</button><button data-view="connections">CONNECTIONS</button><button data-view="authority">AUTHORITY</button><button data-view="settings">SETTINGS / STORAGE</button></nav><div class="rail-note">PERSISTENCE IS YOURS.<br>AUTHORITY IS EXPLICIT.<br><span id="railGrants">CONNECTING…</span></div></aside>
<main class="main" id="main" tabindex="-1"><header class="top"><div><div class="eyebrow">BEAST BOX / COSMIC.CYPHER</div><h1 id="viewTitle">Your private observatory.</h1></div><div class="statusbar"><span class="pill" id="providerPill">provider —</span><span class="pill" id="runtimePill">CONNECTING</span><span class="pill" id="devicePill">DEVICES OFF</span><span class="pill" id="cloudPill">local boundary</span></div></header>
<div class="privacy"><span><b>MASTER PRIVACY</b><br><small>Revoke all grants and stop browser devices. Already-submitted external jobs may continue.</small></span> <button class="danger" id="masterStop">STOP ALL LIVE FLOWS</button></div>
<div id="notice" class="notice hidden" role="status" aria-live="polite"><div class="toolbar"><span id="noticeText"></span><button id="dismissNotice" aria-label="Dismiss notification">DISMISS</button></div></div><div id="handoff" class="warning hidden" role="status">BRAIN CHANGED · SUBSTRATE PRESERVED · AUTHORITY REVOKED — REAUTHORIZE AS NEEDED</div>
<div id="guidedDemo" class="demo-guide hidden"><div class="toolbar"><div><div class="demo-progress" id="demoProgress">GUIDED REFERENCE DEMO</div><h3 id="demoTitle"></h3></div><button id="demoClose">CLOSE GUIDE</button></div><p id="demoCopy"></p><p id="demoReceipt" class="demo-receipt"></p><button id="demoNext">CONTINUE</button></div>
<section id="orbit" class="view active">
 <div class="observatory"><div><div class="eyebrow">PERSISTENT AI / OWNER CONTROLLED</div><h2>Swap the brain.<br><em>Keep the story.</em></h2><p>Your models are replaceable. Your memory, state and provenance have a place to stay.</p><div class="hero-actions"><button data-go="brain" class="primary">OPEN CONVERSATION ↗</button><button data-go="bay">CHOOSE A BRAIN</button></div><div class="hero-caption">YOUR MEMORY · YOUR MODELS · YOUR AUTHORITY</div></div>
 <div class="system-map" aria-label="Live substrate map"><div class="map-node map-brain"><span>ACTIVE BRAIN / REPLACEABLE</span><strong id="mapBrain">Connecting…</strong></div><div class="map-node"><span>MEMORY / DURABLE</span><strong id="mapMemory">—</strong></div><div class="map-node"><span>CNS / STATE HASH</span><strong id="mapState">—</strong></div><div class="map-node map-core"><span>SUBSTRATE CORE</span><strong id="mapCore">—</strong></div><div class="map-caption">HEARTLIGHT / CHECKPOINT <span id="mapCheckpoint">—</span></div></div></div>
 <div class="grid orbit-metrics"><div class="card"><div class="label">Active brain</div><div class="value" id="brainValue">—</div><div class="sub" id="providerValue">—</div></div><div class="card"><div class="label">Memory records</div><div class="value metric-number" id="memoryCount">—</div><div class="sub">Durable substrate</div></div><div class="card"><div class="label">Checkpoint <span id="checkpointSeq">—</span></div><div class="value" id="checkpoint">—</div><div class="sub">SHA-256 / verified chain</div></div><div class="card"><div class="label">Authority grants</div><div class="value metric-number" id="grantCount">—</div><div class="sub">Session only · reset on swap</div></div>
 <div class="card half"><div class="label">Substrate ID</div><div class="value mono" id="systemId">—</div></div><div class="card half"><div class="label">Workspace / boundary</div><div class="value mono" id="orbitWorkspace">No workspace selected</div><div class="sub" id="orbitBoundary">Connecting…</div></div>
 <div class="card full quickpaths"><div><div class="label">THE TWO-BRAIN DEMO</div><h3>New model. Same substrate.</h3><p>See continuity with the real reference fixture. No account or credentials needed.</p></div><button id="demoStart">START GUIDED DEMO ↗</button></div></div></section>
<section id="brain" class="view"><div class="grid"><div class="card full"><div class="label">BRAIN · CONVERSATION</div><div id="swapBanner" class="warning hidden" style="margin:10px 0">BRAIN CHANGED · SUBSTRATE PRESERVED</div><div class="chatlog" id="chatlog" role="log" aria-label="Conversation"><div class="empty" id="chatEmpty">The story continues here.<br><span class="sub">Choose a provider in Brain Bay, then send your first message.<br>The reference fixture is deterministic demonstration output.</span></div></div><div class="composer"><textarea id="chatText" aria-label="Message" maxlength="8192" placeholder="Talk to your system… Ctrl/⌘ + Enter to send"></textarea><button id="sendChat">SEND</button></div><div class="sub">Ordinary chat is durable. Selected temporary context and its answer stay out of durable memory. Your typed message still persists. Remote providers receive selected context only with cloud authority.</div><div id="chatContexts" class="context-picker"></div></div></div></section>
<section id="bay" class="view"><div class="grid"><div class="card full"><div class="label">BRAIN BAY / REPLACEABLE INFERENCE</div><h2>The model clocks in. The story stays.</h2><p class="sub">Choose an adapter, enter a model, then clock it in. One active profile. Cards select provider types; they do not discover installed models.</p>
 <div class="brain-slots" role="group" aria-label="Provider types"><button class="brain-slot" data-provider="reference" aria-pressed="false"><span class="slot-symbol" aria-hidden="true">◉</span><span class="slot-state" id="slotReference">AVAILABLE</span><strong>COSMOS Reference</strong><small>Deterministic fixture<br>No model download · no credentials</small></button><button class="brain-slot" data-provider="ollama" aria-pressed="false"><span class="slot-symbol" aria-hidden="true">◎</span><span class="slot-state" id="slotOllama">CONFIGURE</span><strong>Ollama</strong><small>Local inference<br>Requires your running model server</small></button><button class="brain-slot" data-provider="compatible" aria-pressed="false"><span class="slot-symbol" aria-hidden="true">◇</span><span class="slot-state" id="slotCompatible">CONFIGURE</span><strong>Compatible endpoint</strong><small>Local or authorized remote<br>OpenAI-compatible chat API</small></button></div>
 <div class="toolbar"><div class="label">ACTIVE PROFILE / <span id="bayCurrent">CONNECTING</span></div><span class="pill" id="bayBoundary">—</span></div><div class="fields"><label>Kind<select id="providerKind"><option value="reference">Reference fixture</option><option value="ollama">Ollama</option><option value="compatible">OpenAI-compatible</option></select></label><label>Model<input id="providerModel" value="COSMOS reference" maxlength="256"></label><label>Base URL<input id="providerUrl" placeholder="http://127.0.0.1:11434" maxlength="2048"></label><label>API key environment variable<input id="providerEnv" placeholder="OPTIONAL_ENV_NAME" maxlength="128" autocomplete="off" spellcheck="false"></label></div><label><input type="checkbox" id="allowRemote"> Explicitly allow a configured HTTPS remote endpoint</label><button id="saveProvider" class="primary">CLOCK IN BRAIN</button><p class="sub">Only an environment-variable name belongs here. Configure the actual key on the host. A remote profile requires cloud authority to configure and a fresh grant after identity changes.</p>
 <div class="boundary-strip"><span>MODEL <b>REPLACEABLE</b></span><span>SUBSTRATE <b>PRESERVED</b></span><span>AUTHORITY <b>RESET ON CHANGE</b></span></div><p class="sub">A same-identity re-save preserves grants. There is no silent provider fallback.</p></div></div></section>
<section id="vision" class="view"><div class="grid"><div class="card wide"><div class="label">VISION · LOCAL CAMERA</div><video id="cameraPreview" class="camera" autoplay muted playsinline></video><canvas id="cameraCanvas" class="hidden"></canvas><div style="margin-top:10px"><button id="cameraOn">ENABLE CAMERA</button> <button id="cameraSample">SAMPLE BOUNDED OBSERVATION</button> <button id="cameraOff">STOP CAMERA</button></div></div><div class="card"><div class="label">Boundary</div><div class="value" id="cameraStatus">OFF</div><p class="mono">IMPLEMENTED_NOT_PHYSICALLY_VALIDATED</p><div class="sub">Camera-derived features are not vision understanding. Raw frames stay in this browser in the current implementation.</div></div></div></section>
<section id="listen" class="view"><div class="grid"><div class="card wide"><div class="label">LISTEN · LOCAL MICROPHONE</div><canvas id="audioScope" class="scope" width="900" height="180"></canvas><div style="margin-top:10px"><button id="micOn">ENABLE MIC</button> <button id="micSample">SEND FEATURE SAMPLE</button> <button id="micOff">STOP MIC</button></div></div><div class="card"><div class="label">LIVE MIC</div><div class="value" id="micStatus">OFF</div><p class="mono">IMPLEMENTED_NOT_PHYSICALLY_VALIDATED</p><div class="sub">Raw continuous audio is never posted by this UI. Local RMS features require explicit microphone authority.</div></div></div></section>
<section id="voice" class="view"><div class="grid"><div class="card full"><div class="label">VOICE · LOCAL BROWSER TTS</div><p class="mono">IMPLEMENTED_NOT_PHYSICALLY_VALIDATED</p><textarea id="voiceText" aria-label="Text to speak" maxlength="8192" placeholder="Text to speak"></textarea><label>Local device voice<select id="voiceChoice"></select></label><button id="speak">SPEAK LOCALLY</button> <button id="stopSpeak">STOP VOICE</button><div class="sub">Uses browser speechSynthesis. Authorized custom voice cloning is NOT_ESTABLISHED in the current validated product path. Browser/OS speech voices may use an external service; local-only voices are selected here when available.</div></div></div></section>
<section id="reality" class="view"><div class="grid"><div class="card full"><div class="label">REALITY · SENSOR / BIO LOOP</div><div class="warning">Current browser surface accepts bounded normalized sensor events. Physical Reality Probe hardware remains separate physical validation. Bio observations are nonmedical.</div><label>Normalized observation<textarea id="sensorText" maxlength="4096" placeholder="Describe the measured software observation"></textarea></label><label>Numeric features (JSON array, −1 to 1)<input id="sensorFeatures" value="[0.0]"></label><button id="sensorSend">SEND AUTHORIZED OBSERVATION</button><pre id="realityOut">No live device stream connected. Sensor authority is required.</pre></div></div></section>
<section id="memory" class="view"><div class="grid"><div class="card full"><div class="toolbar"><div><div class="label">MEMORY VAULT / RETAINED RECORDS</div><h2>The story you chose to keep.</h2></div><button id="refreshMemory">REFRESH</button></div><p class="sub">The latest 50 real durable records. Nodes follow record order; they are not inferred neural connections. Select a node to inspect its record.</p><div class="memory-controls"><label>Filter loaded records<input id="memoryQuery" type="search" placeholder="Search text, kind or record ID"></label><label>View<select id="memoryMode"><option value="visual">VISUAL VIEW</option><option value="raw">RAW / TECHNICAL VIEW</option></select></label></div><div id="memoryConstellation" class="memory-constellation" aria-label="Memory record navigation"></div><div id="memoryOut" class="records"><p class="empty">Loading durable records…</p></div><pre id="memoryRaw" class="hidden" aria-label="Raw memory records"></pre></div></div></section>
<section id="trace" class="view"><div class="grid"><div class="card full"><div class="toolbar"><div><div class="label">SYNAPSE TRACE / SYSTEM TRACE</div><h2>Follow the work.</h2></div><button id="refreshTrace">REFRESH</button></div><div class="warning">SYSTEM TRACE · NOT MODEL PRIVATE REASONING<br>System events, not private chain-of-thought. Highlighted stages come from recorded receipts. Dashed stages were not recorded for that event.</div><div id="traceSummary" class="trace-summary"></div><div id="traceOut"></div></div></div></section>
<section id="files" class="view"><div class="grid">
<div class="card half"><div class="label">FILES / CHOOSE THE LIFETIME</div><h2>A file is not a memory.</h2><p class="sub">Inspect locally first. Nothing uploads until you choose ADD CONTEXT. UTF-8 text only, up to 512 KiB per file.</p>
<label>Choose a text file<input type="file" id="fileInput" accept="text/*,.md,.json,.py,.js,.ts,.csv,.yaml,.toml"></label><pre id="fileOut">No file selected. Browser-local inspection only.</pre>
<div class="label" style="margin-top:24px">HOW SHOULD THE BEAST USE THIS?</div><div class="scope-options" role="group" aria-label="File lifetime choices"><button class="scope-choice" data-scope="temporary_attachment" aria-pressed="true"><strong>TEMPORARY ATTACHMENT</strong><small>Only the next interaction you select it for.</small></button><button class="scope-choice" data-scope="conversation_context" aria-pressed="false"><strong>CONVERSATION CONTEXT</strong><small>Available during this server session.</small></button><button class="scope-choice" data-scope="workspace_knowledge" aria-pressed="false"><strong>WORKSPACE KNOWLEDGE</strong><small>A session snapshot from your selected root.</small></button><button class="scope-choice" data-scope="persistent_memory" aria-pressed="false"><strong>PERSISTENT MEMORY</strong><small>Durable storage. Explicit confirmation required.</small></button></div><label>Context scope<select id="contextScope"><option value="temporary_attachment">TEMPORARY ATTACHMENT</option><option value="conversation_context">CONVERSATION CONTEXT</option><option value="workspace_knowledge">WORKSPACE KNOWLEDGE</option><option value="persistent_memory">PERSISTENT MEMORY</option></select></label>
<label>Workspace-relative path (workspace scope only)<input id="contextPath" placeholder="docs/notes.md"></label><div class="warning" id="scopeHelp"></div><button id="addContext" class="primary">ADD CONTEXT</button>
</div><div class="card half"><div class="label">CONTEXT INVENTORY</div><p class="sub">Select staged items beside the chat composer to send them. Session items expire when the server stops. Removing a persistent receipt does not delete durable memory.</p><button id="refreshContext">REFRESH</button><div id="contextOut" class="records"></div></div></div></section>
<section id="workspace" class="view"><div class="grid"><div class="card full"><div class="label">WORKSPACE / REPOSITORY COCKPIT</div><div class="toolbar"><h2>Work inside your boundary.</h2><span class="pill" id="writeState">READ-ONLY BY DEFAULT</span></div><p class="sub">Allow one local directory with FILESYSTEM authority. Reads stay confined to the selected root. Writes require both FILESYSTEM and REPO_WRITE.</p><div class="fields"><label>Local directory<input id="workspaceRoot" placeholder="/home/you/projects/my-project"></label><label>Allowed workspaces<select id="workspaceSelect"><option value="">No allowed roots</option></select></label></div><div class="toolbar"><button id="allowWorkspace">ALLOW WORKSPACE</button><button id="selectWorkspace">SELECT WORKSPACE</button><button id="repoStatus">REPO STATUS</button><button data-go="authority">MANAGE AUTHORITY ↗</button></div><div class="workspace-status"><span class="pill" id="workspaceBranch">BRANCH / NO REPOSITORY</span><span class="pill" id="workspaceWriteGate">WRITE LOCKED</span><button id="grantWrite" class="danger">GRANT WRITE</button><button id="revokeWrite">REVOKE WRITE</button></div><p id="activeRoot" class="mono">No workspace selected</p><details><summary>Repository status / technical details</summary><pre id="repoOut">Select a workspace to inspect branch and repository status.</pre></details></div>
<div class="card"><div class="toolbar"><div class="label">FILE TREE / FIRST 400 ENTRIES</div><button id="refreshTree">REFRESH TREE</button></div><div id="workspaceTree" class="file-tree"></div></div><div class="card wide"><div class="label">BOUNDED FILE EDITOR</div><label>Relative path<input id="workspacePath" placeholder="README.md"></label><button id="readWorkspace">READ FILE</button><label>Content<textarea id="workspaceContent" class="editor" spellcheck="false" placeholder="Select a file to read up to 250,000 bytes"></textarea></label><button id="previewDiff">PREVIEW DIFF</button> <button id="writeWorkspace" class="danger" disabled>WRITE FILE WITH BACKUP</button><p class="sub">READ-ONLY BY DEFAULT. Preview compares your editor with the current file without writing. A write changes the selected file and creates a local backup.</p><div class="diff-view" id="diffOut" aria-label="File diff preview">No preview requested.</div></div>
<div class="card full"><div class="label">WORKSPACE SEARCH</div><label>Find text<input id="workspaceQuery" type="search" maxlength="256" placeholder="Search within the selected root"></label><button id="searchWorkspace">SEARCH</button><p class="sub">Case-insensitive text search. Up to 50 hits, 2,500 candidate files and 8 MiB of readable content. Large files and symlinks are skipped.</p><div id="searchOut" class="search-hits" aria-live="polite"></div></div><div class="card full"><div class="label">BOUNDED TOOL RUNNER</div><p class="sub">TOOLS authority required. These fixed Git commands are read-only. Arbitrary shell, commit and push remain owner terminal actions.</p><select id="toolCommand" aria-label="Read-only command"><option value='["git","status","--short","--branch"]'>git status --short --branch</option><option value='["git","diff","--stat"]'>git diff --stat</option><option value='["git","log","-5","--oneline"]'>git log -5 --oneline</option></select><button id="runTool">RUN AUTHORIZED COMMAND</button><pre id="toolOut">No command run.</pre></div></div></section>
<section id="qbay" class="view"><div class="grid"><div class="card half"><div class="label">Q-BAY · IBM / AZURE</div><button id="refreshResources">CHECK CONFIGURATION</button><pre id="resourcesOut">—</pre></div><div class="card half"><div class="label">EXPERIMENTAL / BLOCKED_EXTERNAL UNTIL VALIDATED</div><label>Provider<select id="qProvider"><option value="ibm">IBM hardware adapter</option><option value="azure">Azure IonQ simulator</option></select></label><label>Shots<input id="qShots" type="number" min="1" max="1024" value="128"></label><button id="qRun">SUBMIT AUTHORIZED JOB</button><div class="sub">Requires a separate quantum_live authority grant and host credentials. Features → numeric input → optional control mapping → provider job → result → normalized event → CNS / memory. This submission uses the existing adapter workload; it does not map live audio/light into qubits. Quantum provenance ≠ quantum advantage.</div></div></div></section>
<section id="connections" class="view"><div class="grid"><div class="card full"><div class="label">CONNECTIONS</div><pre id="connectionsOut">IBM / Azure status reports configuration only. Ollama and compatible model endpoints are configured in Brain Bay. Secret values remain host configuration.</pre></div></div></section>
<section id="authority" class="view"><div class="grid"><div class="card full"><div class="label">AUTHORITY / YOU HOLD THE KEYS</div><h2>Continuity is portable. Permission is earned.</h2><div class="authority-manifest">STATE MAY TRAVEL.<br>INFORMATION MAY TRAVEL.<br><strong>AUTHORITY DOES NOT TRAVEL AUTOMATICALLY.</strong></div><div class="authority-summary"><span class="pill" id="authorityCount">CONNECTING</span><span class="pill">SESSION ONLY</span><span class="pill">REVOKED ON BRAIN CHANGE</span></div><p class="sub">Grants last for this server session and the current brain identity. Changing brains revokes every grant; re-saving the same identity preserves them.</p><div id="authorityList"></div></div></div></section>
<section id="settings" class="view"><div class="grid"><div class="card full"><div class="label">SETTINGS / STORAGE / PORTABLE CONTINUITY</div><div class="capsule-mark" style="margin-top:20px">CONTINUITY CAPSULE</div><h2>Take the story with you.</h2><p class="sub">A portable, verified snapshot of memory and software state. Keep the technical receipt with your backup process.</p><p>STATE MAY TRAVEL. INFORMATION MAY TRAVEL. AUTHORITY DOES NOT TRAVEL AUTOMATICALLY.</p><div class="trust-cells"><div class="trust-cell"><div class="label">AUTHORITY</div><b id="storageAuthority">CONNECTING</b><small>Grants remain session-local.</small></div><div class="trust-cell"><div class="label">CREDENTIALS</div><b id="storageCredentials">CONNECTING</b><small>Host configuration is excluded.</small></div><div class="trust-cell"><div class="label">ENCRYPTION</div><b id="storageEncryption">CONNECTING</b><small>Use host/storage encryption.</small></div></div><button id="refreshStorage">REFRESH STORAGE</button><dl id="storageFacts" class="facts"></dl><div class="warning">Encryption: NOT_ESTABLISHED. Host/storage encryption recommended. Protect exported bundles like your private memory.</div></div>
<div class="card half"><div class="capsule-mark">01 / EXPORT CAPSULE</div><h3>Give continuity a destination.</h3><div class="label">EXPORT SNAPSHOT</div><label>New destination directory<input id="exportDestination" placeholder="/home/you/backups/beast-snapshot"></label><button id="exportSnapshot">EXPORT SNAPSHOT</button><p class="sub">Creates a bundle at a new local path. Save its manifest hash separately for later verification.</p></div><div class="card half"><div class="capsule-mark">02 / VERIFY &amp; RESTORE CAPSULE</div><h3>Trust the receipt. Check the hash.</h3><div class="label">VERIFY / IMPORT SNAPSHOT</div><label>Bundle directory<input id="snapshotBundle" placeholder="/home/you/backups/beast-snapshot"></label><label>Trusted manifest SHA-256<input id="snapshotHash" maxlength="64" placeholder="64-character digest from export receipt"></label><button id="verifySnapshot">VERIFY SNAPSHOT</button><label>New restore directory<input id="importDestination" placeholder="/home/you/restored-beast"></label><button class="danger" id="importSnapshot">IMPORT SNAPSHOT</button><p class="sub">Import verifies integrity and restores to a new directory. It does not overwrite or switch the running substrate. Start Beast Box with the restored data directory afterward.</p></div><div class="card full"><div class="label">STORAGE RECEIPT</div><pre id="storageOut">No storage operation performed.</pre></div><div class="card full"><div class="label">FEATURE TRUTH MATRIX</div><p class="sub">IMPLEMENTED_AND_TESTED describes software checks. Device and hardware validation remain separately classified.</p><div id="featureMatrix" class="records"></div></div></div></section>
<footer>BEAST BOX / COSMIC.CYPHER <span>SWAP THE BRAIN. KEEP THE STORY. · LOCAL OWNER CONSOLE</span></footer>
</main></div><script>
const sessionKey=__BEAST_SESSION__;
const $=id=>document.getElementById(id);
let orbit=null,cameraStream=null,audioStream=null,audioCtx=null,analyser=null,stagedFile=null,contextRecords=[];
let deviceEpoch=0,providerHydrated=false,currentView='orbit';
let activeProfile=null,memoryRecords=[],authoritySignature='',demo=null;
const viewTitles={orbit:'Your private observatory.',brain:'The conversation continues.',bay:'Brain Bay.',vision:'A window into your world.',listen:'Listen, with permission.',voice:'Give the story a voice.',reality:'Observe. Normalize. Record.',memory:'Memory Vault.',trace:'Synapse Trace.',files:'You choose what stays.',workspace:'Your engineering cockpit.',qbay:'Q-Bay / experimental.',connections:'Your connections.',authority:'You hold the keys.',settings:'Storage & continuity.'};
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=String(text);return node};
const shortHash=value=>String(value||'—').slice(0,16);

function notify(message,error=false){$('noticeText').textContent=message;$('notice').className='notice'+(error?' error':'')}
$('dismissNotice').onclick=()=>$('notice').classList.add('hidden');
async function api(path,method='GET',body=null){
 const opt={method,headers:{'X-Beast-Session':sessionKey}};
 if(body!==null){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(body)}
 const response=await fetch(path,opt);let data={};try{data=await response.json()}catch{}
 if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;
}
function action(id,fn){
 $(id).onclick=async()=>{const button=$(id),label=button.textContent;button.disabled=true;button.setAttribute('aria-busy','true');button.textContent=id==='saveProvider'?'CLOCKING IN NEW BRAIN…':'WORKING…';
 try{await fn()}catch(e){notify(e.message,true)}finally{button.textContent=label;button.disabled=false;button.removeAttribute('aria-busy');if(id==='writeWorkspace')updateWriteState()}}
}
function output(id,data){$(id).textContent=JSON.stringify(data,null,2)}
async function show(view){
 if(!document.querySelector('#nav button[data-view="'+view+'"]'))return;
 currentView=view;$('viewTitle').textContent=viewTitles[view];
 document.querySelectorAll('.view').forEach(node=>node.classList.toggle('active',node.id===view));
 document.querySelectorAll('#nav button').forEach(button=>{const active=button.dataset.view===view;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});
 try{const loader={memory:loadMemory,trace:loadTrace,workspace:loadWorkspace,files:loadContexts,settings:loadStorage,connections:loadResources,qbay:loadResources};if(loader[view])await loader[view]()}catch(e){notify(e.message,true)}
}
document.querySelectorAll('#nav button').forEach(button=>button.onclick=()=>show(button.dataset.view));
document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>show(button.dataset.go));
$('nav').onkeydown=e=>{if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...$('nav').querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(index<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)+buttons.length)%buttons.length;buttons[next].focus();show(buttons[next].dataset.view)};
function addMsg(role,text,metadata=''){ $('chatEmpty')?.remove();const node=document.createElement('div');node.className='msg '+role;node.textContent=text;if(metadata){const meta=document.createElement('div');meta.className='sub';meta.textContent=metadata;node.append(meta)}$('chatlog').append(node);$('chatlog').scrollTop=$('chatlog').scrollHeight}
function updateWriteState(){
 const writable=!!(orbit?.authority.filesystem&&orbit?.authority.repo_write);
 $('writeWorkspace').disabled=!writable;$('writeState').textContent=writable?'WRITE AUTHORIZED':'READ-ONLY BY DEFAULT';$('writeState').classList.toggle('live',writable);
 $('workspaceWriteGate').textContent=writable?'WRITE ENABLED — SESSION ONLY':'WRITE LOCKED';$('workspaceWriteGate').classList.toggle('live',writable);
 $('grantWrite').disabled=writable;$('revokeWrite').disabled=!orbit?.authority.repo_write;
}
function localStopCamera(){deviceEpoch++;if(cameraStream)cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;$('cameraPreview').srcObject=null;$('cameraStatus').textContent='OFF';deviceIndicators()}
function localStopMic(){deviceEpoch++;if(audioStream)audioStream.getTracks().forEach(track=>track.stop());audioStream=null;if(audioCtx)audioCtx.close().catch(()=>{});audioCtx=null;analyser=null;$('micStatus').textContent='OFF';deviceIndicators()}
function deviceIndicators(){const live=!!(cameraStream||audioStream);$('devicePill').textContent=[cameraStream?'CAMERA LIVE':'',audioStream?'MIC LIVE':''].filter(Boolean).join(' · ')||'DEVICES OFF';$('devicePill').classList.toggle('live',live)}
async function loadOrbit(){
 orbit=await api('/api/orbit');const runtime=orbit.runtime;
 $('systemId').textContent=runtime.system_id;$('checkpoint').textContent=shortHash(runtime.checkpoint_sha256)+'…';$('checkpoint').title=runtime.checkpoint_sha256;
 $('memoryCount').textContent=runtime.memory.memories;$('checkpointSeq').textContent='#'+runtime.sequence;
 const grants=Object.values(orbit.authority).filter(Boolean).length;$('grantCount').textContent=grants;$('railGrants').textContent=grants+' / 9 GRANTS ENABLED';
 $('runtimePill').textContent=runtime.valid?'SUBSTRATE VERIFIED':'SUBSTRATE INVALID';
 $('mapMemory').textContent=runtime.memory.memories+' retained records';$('mapState').textContent=shortHash(runtime.state_sha256)+'…';$('mapState').title=runtime.state_sha256;
 $('mapCore').textContent=shortHash(runtime.system_id);$('mapCore').title=runtime.system_id;$('mapCheckpoint').textContent='#'+runtime.sequence;
 $('orbitWorkspace').textContent=orbit.workspace?.root||'No workspace selected';
 if(!orbit.authority.camera&&cameraStream)localStopCamera();if(!orbit.authority.microphone&&audioStream)localStopMic();
 renderAuthority(orbit.authority);updateWriteState();
 const data=await api('/api/provider'),profile=data.profile;activeProfile=profile;
 $('brainValue').textContent=profile.model;$('mapBrain').textContent=profile.model;$('providerValue').textContent=profile.kind;$('providerPill').textContent=profile.kind+' · '+profile.model;
 $('bayCurrent').textContent=profile.kind+' / '+profile.model;$('bayBoundary').textContent=profile.kind==='reference'?'REFERENCE FIXTURE / NO NETWORK':data.network_boundary+' ENDPOINT';
 $('cloudPill').textContent=orbit.authority.cloud?'CLOUD AUTHORIZED':'CLOUD DENIED';
 $('orbitBoundary').textContent=profile.kind==='reference'?'Reference fixture · inference stays in this process':data.network_boundary==='REMOTE'?'Remote inference · '+(orbit.authority.cloud?'cloud authorized':'cloud authority required'):'Local inference endpoint · loopback boundary';
 if(!providerHydrated){hydrateProfile(profile);providerHydrated=true}
 updateProviderCards();
 const box=$('featureMatrix');box.replaceChildren();Object.entries(orbit.capabilities).forEach(([name,feature])=>{const node=el('div','record');node.append(el('strong','',name.replaceAll('_',' ')),el('div','meta',feature.status+' · '+feature.source));box.append(node)});
}
function hydrateProfile(profile){$('providerKind').value=profile.kind;$('providerModel').value=profile.model;$('providerUrl').value=profile.base_url;$('providerEnv').value=profile.api_key_env||'';$('allowRemote').checked=profile.allow_remote}
function updateProviderCards(){document.querySelectorAll('[data-provider]').forEach(button=>{button.setAttribute('aria-pressed',String(button.dataset.provider===$('providerKind').value));button.querySelector('.slot-state').textContent=button.dataset.provider===activeProfile?.kind?'CURRENT TYPE':button.dataset.provider==='reference'?'AVAILABLE':'CONFIGURE'})}
document.querySelectorAll('[data-provider]').forEach(button=>button.onclick=()=>{
 const kind=button.dataset.provider;if(kind===activeProfile?.kind)hydrateProfile(activeProfile);else hydrateProfile({kind,model:kind==='reference'?'COSMOS reference':'',base_url:kind==='ollama'?'http://127.0.0.1:11434':kind==='compatible'?'http://127.0.0.1:1234/v1':'',allow_remote:false});updateProviderCards();$('providerModel').focus();
});
$('providerKind').onchange=updateProviderCards;
const authorityPurpose={
 camera:['Camera capture','Allows explicit browser capture and bounded brightness observations. Raw frames stay in the browser.'],
 microphone:['Microphone capture','Allows explicit browser capture and bounded RMS observations. Raw audio stays in the browser.'],
 sensors:['Normalized sensor input','Allows owner-submitted numeric observations to enter the runtime. No physical device is connected by this grant.'],
 cloud:['External model transport','Allows the configured remote provider to receive the current prompt and selected context.'],
 filesystem:['Workspace allowlisting & writes','Allows the owner to allowlist a root. Required again, with REPO_WRITE, to write files. Already-allowlisted reads remain available.'],
 repo_write:['Workspace file changes','Allows confined file writes with FILESYSTEM. Backups are local. Commit and push remain owner terminal actions.'],
 tools:['Bounded command runner','Allows the listed read-only Git commands in the selected repository. Does not grant a shell.'],
 quantum_live:['Experimental external jobs','Allows optional IBM/Azure submission using host configuration. A grant does not establish hardware access.'],
 external_integrations:['External integration boundary','Reserved owner permission for separately configured integrations. No integration is activated by the grant alone.']
};
function renderAuthority(authority){
 $('authorityCount').textContent=Object.values(authority).filter(Boolean).length+' / 9 ENABLED';
 const signature=JSON.stringify(authority);if(signature===authoritySignature)return;authoritySignature=signature;
 const box=$('authorityList');box.replaceChildren();Object.entries(authority).forEach(([name,on])=>{
  const row=el('div','authority-row'+(on?' granted':'')),copy=el('div'),title=el('strong');title.append(el('span','gate-dot'),document.createTextNode(name.toUpperCase()+' · '+(on?'GRANTED':'DENIED')));
  copy.append(title,el('div','sub',authorityPurpose[name][0]+' / '+authorityPurpose[name][1]),el('p','authority-meta','SESSION ONLY · REVOKED ON BRAIN CHANGE · NOT EXPORTED'));
  const button=el('button',on?'danger':'',on?'REVOKE':'GRANT');button.onclick=async()=>{button.disabled=true;try{if(!on&&!confirm('Grant '+name+' to the current brain for this server session?'))return;if(on&&name==='camera')localStopCamera();if(on&&name==='microphone')localStopMic();await api('/api/authority','POST',{action:on?'revoke':'grant',name});await loadOrbit()}catch(e){notify(e.message,true)}finally{button.disabled=false}};row.append(copy,button);box.append(row);
 });
}
async function grant(name){await api('/api/authority','POST',{action:'grant',name});await loadOrbit()}
async function revoke(name){await api('/api/authority','POST',{action:'revoke',name});await loadOrbit()}
action('masterStop',async()=>{localStopCamera();localStopMic();window.speechSynthesis?.cancel();await api('/api/authority','POST',{action:'master_stop'});await loadOrbit();notify('All authority revoked. Browser devices stopped. Already-submitted external jobs may continue.')});
action('sendChat',async()=>{const text=$('chatText').value.trim();if(!text)return;const context_ids=[...$('chatContexts').querySelectorAll('input:checked')].map(input=>Number(input.value));addMsg('user',text);const result=await api('/api/chat','POST',{text,context_ids});$('chatText').value='';const label=result.provider.kind+' / '+result.provider.model+' · '+(result.response_persistent?'durable turn':'context answer · not persisted');addMsg('assistant',result.result.response,label);$('voiceText').value=result.result.response;await loadOrbit();await loadContexts();await demoChat(result,text)});
$('chatText').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();if(!$('sendChat').disabled)$('sendChat').click()}};
action('saveProvider',async()=>{
 const before=await api('/api/orbit');
 const result=await api('/api/provider','POST',{kind:$('providerKind').value,model:$('providerModel').value,base_url:$('providerUrl').value,allow_remote:$('allowRemote').checked,api_key_env:$('providerEnv').value||null});
 if(result.brain_changed){localStopCamera();localStopMic();window.speechSynthesis?.cancel();$('handoff').classList.remove('hidden');notify('Brain changed. Substrate preserved. Authority revoked — reauthorize as needed.')}else notify('Same brain saved. Existing authority preserved.');
 await loadOrbit();if(demo&&result.profile.kind!=='reference'){demo=null;$('guidedDemo').classList.add('hidden');notify('Reference guide closed. The newly configured provider is active.')}if(demo&&demo.step===2&&result.brain_changed){
  const preserved=['system_id','memory_digest','checkpoint_sha256','state_sha256'].every(key=>before.runtime[key]===orbit.runtime[key]);
  if(!preserved||Object.values(orbit.authority).some(Boolean))throw new Error('Handoff verification failed. Inspect the system trace.');
  demo.step=3;demo.receipt='BRAIN CHANGED · SUBSTRATE PRESERVED · AUTHORITY RESET · system '+shortHash(orbit.runtime.system_id);renderDemo();
 }await show('brain');
});
async function startCamera(){if(cameraStream)return;try{cameraStream=await acquireDevice('camera');deviceIndicators();document.getElementById('cameraPreview').srcObject=cameraStream;document.getElementById('cameraStatus').textContent='CAMERA LIVE'}catch(e){await revoke('camera');throw e}}async function stopCamera(){localStopCamera();await revoke('camera')}
async function sampleCamera(){if(!cameraStream)throw new Error('camera is off');const v=document.getElementById('cameraPreview'),c=document.getElementById('cameraCanvas');if(!v.videoWidth)throw new Error('Camera is starting; try again in a moment');c.width=320;c.height=180;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data;let sum=0,n=0;const stride=Math.max(4,Math.floor(d.length/4096/4)*4);for(let i=0;i<d.length;i+=stride){sum+=(d[i]+d[i+1]+d[i+2])/(3*255);n++}const mean=n?sum/n:0;return api('/api/event','POST',{modality:'camera',event:{schema:'sensor-event-v1',source:'software-event',text:JSON.stringify({source:'browser-camera',mode:'local-brightness-summary',mean}),features:[mean*2-1]}})}
action('cameraOn',startCamera);action('cameraOff',stopCamera);action('cameraSample',async()=>{await sampleCamera();notify('Bounded brightness observation submitted.');await loadOrbit()});
function drawAudio(){if(!analyser)return;const a=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(a);const c=document.getElementById('audioScope'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.beginPath();for(let i=0;i<a.length;i++){const px=i/(a.length-1)*c.width,py=a[i]/255*c.height;i?x.lineTo(px,py):x.moveTo(px,py)}x.strokeStyle='#79ded5';x.stroke();requestAnimationFrame(drawAudio)}
async function startMic(){if(audioStream)return;try{audioStream=await acquireDevice('microphone');deviceIndicators();audioCtx=new AudioContext();analyser=audioCtx.createAnalyser();analyser.fftSize=1024;audioCtx.createMediaStreamSource(audioStream).connect(analyser);document.getElementById('micStatus').textContent='MIC LIVE';drawAudio()}catch(e){localStopMic();await revoke('microphone');throw e}}async function stopMic(){localStopMic();await revoke('microphone')}
async function sampleMic(){if(!analyser)throw new Error('microphone is off');const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);let s=0;for(const v of a)s+=v*v;const rms=Math.sqrt(s/a.length),bounded=Math.max(-1,Math.min(1,rms*2-1));return api('/api/event','POST',{modality:'microphone',event:{schema:'sensor-event-v1',source:'software-event',text:JSON.stringify({source:'browser-microphone',mode:'local-rms-feature',rms}),features:[bounded]}})}
action('micOn',startMic);action('micOff',stopMic);action('micSample',async()=>{await sampleMic();notify('Bounded RMS observation submitted.');await loadOrbit()});

// A permission dialog can finish after Stop or a model handoff. Discard stale streams.
async function acquireDevice(kind){const epoch=deviceEpoch;await grant(kind==='camera'?'camera':'microphone');const stream=await navigator.mediaDevices.getUserMedia(kind==='camera'?{video:true,audio:false}:{audio:true,video:false});try{const status=await api('/api/orbit');if(epoch!==deviceEpoch||!status.authority[kind==='camera'?'camera':'microphone'])throw new Error('Device enable was cancelled by a privacy action');return stream}catch(error){stream.getTracks().forEach(track=>track.stop());throw error}}
async function loadMemory(){memoryRecords=(await api('/api/memory')).records;renderMemory()}
function renderMemory(){
 const query=$('memoryQuery').value.toLowerCase(),records=memoryRecords.filter(r=>JSON.stringify(r).toLowerCase().includes(query));
 const raw=$('memoryMode').value==='raw';$('memoryOut').classList.toggle('hidden',raw);$('memoryRaw').classList.toggle('hidden',!raw);$('memoryConstellation').classList.toggle('hidden',raw);
 output('memoryRaw',records);const box=$('memoryOut'),nodes=$('memoryConstellation');box.replaceChildren();nodes.replaceChildren();
 if(!records.length){box.append(el('p','empty',memoryRecords.length?'No loaded records match this filter.':'No durable records yet. Ordinary chat or explicit PERSISTENT MEMORY creates records.'));return}
 let group='';records.forEach(record=>{
  const stamp=new Date(record.created_at*1000),today=stamp.toDateString()===new Date().toDateString();
  const dateLabel=today?'TODAY':stamp.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}).toUpperCase();
  if(group!==dateLabel){box.append(el('div','memory-date',dateLabel));group=dateLabel}
  const node=el('article','memory-record');node.id='retained-memory-'+record.id;node.tabIndex=-1;
  const title=record.metadata?.name||record.kind.replaceAll('_',' ');node.append(el('strong','',title+' · #'+record.id),el('div','meta',stamp.toLocaleString()+' · '+record.kind+' · DURABLE_SUBSTRATE'),el('p','',record.text));
  const details=el('details'),summary=el('summary','','DETAILS / hash, source & metadata');details.append(summary,el('div','meta','TEXT SHA-256 '+record.sha256),el('div','meta','SOURCE RECORDS '+(record.source_ids.join(', ')||'none')+' · PERSISTENT YES'),el('pre','',JSON.stringify(record.metadata,null,2)));node.append(details);box.append(node);
  const dot=el('button','memory-node',record.id);dot.setAttribute('aria-label','Inspect memory record '+record.id);dot.title=title+' · #'+record.id;dot.onclick=()=>{node.focus({preventScroll:true});node.scrollIntoView({block:'center',behavior:'auto'});details.open=true};nodes.append(dot);
 });
}
$('memoryQuery').oninput=renderMemory;$('memoryMode').onchange=renderMemory;
const stageNames={normalize:'NORMALIZE',memory_lookup:'MEMORY LOOKUP',r12_routing:'R12 ROUTING',state_cns:'CNS / STATE',model:'MODEL',policy:'POLICY',bounded_output:'BOUNDED OUTPUT',memory_write:'MEMORY WRITE',provenance:'PROVENANCE',checkpoint:'CHECKPOINT',explicit_persist:'EXPLICIT PERSIST'};
async function loadTrace(){
 const data=await api('/api/trace'),box=$('traceOut');box.replaceChildren();
 $('traceSummary').textContent=data.events.length+' retained checkpoints · '+data.session_events.length+' session events · newest first';
 [...data.events].reverse().forEach((event,index)=>{
  const node=el('details','trace-node');node.open=index===0;const title=el('summary','','checkpoint #'+event.sequence+' / '+(event.model.model||'system')+' / '+shortHash(event.checkpoint_sha256));node.append(title);
  const stages=el('div','trace-stages');(event.stages.length?event.stages:['genesis']).forEach(stage=>stages.append(el('span','trace-stage'+(stage==='checkpoint'?' checkpoint':''),stageNames[stage]||stage.toUpperCase())));
  if(!event.stages.includes('model'))stages.append(el('span','trace-stage inactive','MODEL / NOT RECORDED'));
  node.append(stages,el('div','meta','PROVIDER '+(event.model.provider||'not recorded')+' · MEMORY IDS '+(event.routing.memory_ids?.join(', ')||'none recorded')));
  const technical=el('details');technical.append(el('summary','','DETAILS / routing, policy & hashes'),el('pre','',JSON.stringify(event,null,2)));node.append(technical);box.append(node);
 });
 if(data.session_events.length){const section=el('div','session-events');section.append(el('h3','','Authority & handoffs'),el('p','sub','Session events are bounded owner receipts. They do not travel in a capsule.'));[...data.session_events].reverse().forEach(event=>{const node=el('details','trace-node session');node.append(el('summary','','SESSION / '+event.kind.replaceAll('_',' ')+(event.name?' / '+event.name:'')+(event.model?' / '+event.model:'')),el('pre','',JSON.stringify(event,null,2)));section.append(node)});box.append(section)}
 if(!box.children.length)box.textContent='No events yet. System operations will appear here.';
 if(demo?.step===4&&data.events.some(event=>event.routing.memory_ids?.includes(demo.memoryId))){demo.step=5;demo.receipt='Verified: record #'+demo.memoryId+' appears in actual routing receipts.';renderDemo()}
}
async function loadResources(){const data=await api('/api/resources');output('resourcesOut',data);output('connectionsOut',data)}
action('refreshMemory',loadMemory);action('refreshTrace',loadTrace);action('refreshResources',loadResources);
action('sensorSend',async()=>{const features=JSON.parse($('sensorFeatures').value);output('realityOut',await api('/api/event','POST',{modality:'sensor',event:{schema:'sensor-event-v1',source:'software-event',text:$('sensorText').value,features}}));await loadOrbit()});
action('qRun',async()=>{if(!confirm('Submit one external experimental workload? This may consume provider quota and cannot be cancelled here.'))return;output('resourcesOut',await api('/api/quantum','POST',{provider:$('qProvider').value,shots:Number($('qShots').value)}));await loadOrbit()});
function localVoices(){return window.speechSynthesis?.getVoices().filter(voice=>voice.localService)||[]}
function loadVoices(){const select=$('voiceChoice');select.replaceChildren();localVoices().forEach(voice=>{const option=document.createElement('option');option.value=voice.voiceURI;option.textContent=voice.name+' · '+voice.lang;select.append(option)});if(!select.children.length){const option=document.createElement('option');option.textContent='No local voice available';select.append(option)}}
if(window.speechSynthesis){speechSynthesis.onvoiceschanged=loadVoices;loadVoices()}
action('speak',async()=>{const voice=localVoices().find(item=>item.voiceURI===$('voiceChoice').value);if(!voice)throw new Error('No local browser/OS voice available. Install one on this device.');speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance($('voiceText').value);utterance.voice=voice;speechSynthesis.speak(utterance)});action('stopSpeak',async()=>window.speechSynthesis?.cancel());
const scopeCopy={temporary_attachment:'Nonpersistent. Available for one selected successful chat turn, then removed. The attachment and its answer are not stored; your typed message still persists.',conversation_context:'Nonpersistent. Kept in server memory until removed or server shutdown. Select it explicitly for each chat turn.',workspace_knowledge:'Nonpersistent. Reads the selected relative path through the existing confined workspace. Select this session snapshot explicitly for chat.',persistent_memory:'Permanent. Explicit confirmation is required. The text enters durable memory, retrieval and portable exports.'};
function updateScope(){const scope=$('contextScope').value;$('scopeHelp').textContent=scopeCopy[scope];$('addContext').className=scope==='persistent_memory'?'danger':'primary';document.querySelectorAll('[data-scope]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.scope===scope)));$('contextPath').disabled=scope!=='workspace_knowledge'}
document.querySelectorAll('[data-scope]').forEach(button=>button.onclick=()=>{$('contextScope').value=button.dataset.scope;updateScope()});
$('contextScope').onchange=updateScope;updateScope();
$('fileInput').onchange=async event=>{stagedFile=null;try{const file=event.target.files[0];if(!file)return;if(file.size>512*1024)throw new Error('File exceeds 512 KiB. Choose a smaller UTF-8 text file.');const bytes=await file.arrayBuffer();const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(!text||text.includes('\0'))throw new Error('Choose nonempty UTF-8 text, not a binary file.');const hash=await crypto.subtle.digest('SHA-256',bytes);stagedFile={name:file.name,text};output('fileOut',{name:file.name,bytes:file.size,sha256:[...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join(''),scope:'BROWSER_LOCAL_INSPECTION',lifetime:'UNTIL_TAB_CLOSE',persistent:false});}catch(e){notify(e.message,true)}};
action('addContext',async()=>{const scope=$('contextScope').value;let body={scope};if(scope==='workspace_knowledge')body.path=$('contextPath').value;else{if(!stagedFile)throw new Error('Choose a UTF-8 text file first.');Object.assign(body,stagedFile)}if(scope==='persistent_memory'){if(!confirm('Permanently store this file in memory and future portable exports?'))return;body.confirm_persist=true}const result=await api('/api/context','POST',body);notify(result.persistent?'File explicitly saved in durable memory.':'Context staged. Select it beside the chat composer to send it.');await loadContexts();await loadOrbit()});
async function loadContexts(){const selected=new Set([...$('chatContexts').querySelectorAll('input:checked')].map(input=>Number(input.value)));contextRecords=(await api('/api/context')).contexts;const box=$('contextOut'),picker=$('chatContexts');box.replaceChildren();picker.replaceChildren();if(!contextRecords.length)box.textContent='No staged context. Files stay browser-local until you add them.';contextRecords.forEach(record=>{const node=document.createElement('div');node.className='record';const title=document.createElement('strong');title.textContent=record.name;const meta=document.createElement('div');meta.className='meta';meta.textContent=record.scope.toUpperCase()+' · '+record.bytes+' bytes · '+record.lifetime+' · '+(record.persistent?'PERSISTED':'NOT PERSISTED')+'\nSHA-256 '+record.sha256;const remove=document.createElement('button');remove.textContent=record.persistent?'DISMISS RECEIPT':'REMOVE CONTEXT';remove.onclick=async()=>{try{await api('/api/context/remove','POST',{id:record.id});await loadContexts()}catch(e){notify(e.message,true)}};node.append(title,meta,remove);box.append(node);if(!record.persistent){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=record.id;input.checked=selected.has(record.id);label.append(input,document.createTextNode(' Send '+record.name+' · '+record.scope.replaceAll('_',' ')));picker.append(label)}})}
action('refreshContext',loadContexts);
async function loadWorkspace(){
 const data=await api('/api/workspace');$('activeRoot').textContent=data.selected||'No workspace selected';const select=$('workspaceSelect'),selectedPath=$('workspacePath').value;select.replaceChildren();
 if(!data.allowlist.length){const option=el('option','','No allowed roots');option.value='';select.append(option)}
 data.allowlist.forEach(root=>{const option=el('option','',root);option.value=root;option.selected=root===data.selected;select.append(option)});
 const tree=$('workspaceTree');tree.replaceChildren();data.tree.forEach(path=>{if(path==='... tree truncated ...'){tree.append(el('p','sub',path));return}const button=el('button',path===selectedPath?'selected':'',path);button.onclick=async()=>{try{$('workspacePath').value=path;await readWorkspace();tree.querySelectorAll('button').forEach(item=>item.classList.toggle('selected',item===button))}catch(e){notify(e.message,true)}};tree.append(button)});
 if(!data.tree.length)tree.append(el('p','sub',data.selected?'No files to display.':'Allow and select a directory to open its file tree.'));
 updateWriteState();if(data.selected)await loadRepoStatus();else $('workspaceBranch').textContent='BRANCH / NO REPOSITORY';
}
async function loadRepoStatus(){const data=await api('/api/workspace/status');output('repoOut',data);const status=data.status.stdout||'';$('workspaceBranch').textContent=data.is_git_repo?'BRANCH / '+(status.split('\n')[0].replace(/^## /,'')||'not reported'):'NO REPOSITORY IN SELECTED ROOT'}
async function readWorkspace(){const data=await api('/api/workspace/read','POST',{path:$('workspacePath').value});$('workspaceContent').value=data.content;$('diffOut').textContent='No preview requested for this file.'}
action('allowWorkspace',async()=>{await api('/api/workspace/allow','POST',{root:$('workspaceRoot').value});await loadWorkspace();notify('Workspace allowlisted. Select it to open its file tree.')});
action('selectWorkspace',async()=>{await api('/api/workspace/select','POST',{root:$('workspaceSelect').value});await loadWorkspace();await loadOrbit()});
action('repoStatus',loadRepoStatus);action('refreshTree',loadWorkspace);action('readWorkspace',readWorkspace);
action('grantWrite',async()=>{if(!confirm('Enable FILESYSTEM and REPO_WRITE for this brain and server session? File writes change your selected workspace.'))return;await grant('filesystem');await grant('repo_write');notify('Write enabled — session only. A brain change locks writes again.')});
action('revokeWrite',async()=>{await revoke('repo_write');notify('Write locked. Read-only workspace access remains available.')});
action('previewDiff',async()=>{const data=await api('/api/workspace/diff','POST',{path:$('workspacePath').value,content:$('workspaceContent').value}),box=$('diffOut');box.replaceChildren();if(!data.diff){box.textContent='No changes. The editor matches the current file.';return}data.diff.split('\n').forEach(line=>box.append(el('span','diff-line'+(line.startsWith('+')?' added':line.startsWith('-')?' removed':''),line)));notify('Preview ready. No files were changed.')});
action('searchWorkspace',async()=>{const data=await api('/api/workspace/search','POST',{query:$('workspaceQuery').value}),box=$('searchOut');box.replaceChildren();if(!data.hits.length)box.textContent='No matches within the bounded search.';data.hits.forEach(hit=>{const button=el('button','',hit.path+':'+hit.line);button.append(el('small','',hit.text));button.onclick=async()=>{try{$('workspacePath').value=hit.path;await readWorkspace();$('workspaceContent').focus()}catch(e){notify(e.message,true)}};box.append(button)})});
action('writeWorkspace',async()=>{if(!confirm('Write '+$('workspacePath').value+' in the selected workspace, with a backup?'))return;const receipt=await api('/api/workspace/write','POST',{path:$('workspacePath').value,content:$('workspaceContent').value});output('toolOut',receipt);notify('File written. Backup: '+(receipt.backup||'new file'));await loadWorkspace()});
action('runTool',async()=>output('toolOut',await api('/api/workspace/run','POST',{argv:JSON.parse($('toolCommand').value)})));

async function loadStorage(){const data=await api('/api/storage');$('storageAuthority').textContent=data.authority;$('storageCredentials').textContent=data.credentials;$('storageEncryption').textContent=data.encryption.status;const facts=$('storageFacts');facts.replaceChildren();[['SUBSTRATE LOCATION',data.substrate_location],['SYSTEM ID',data.system_id],['MEMORY COUNT',data.memory_records],['CHECKPOINT SEQUENCE',data.checkpoint_sequence],['LATEST CHECKPOINT HASH',data.checkpoint_sha256],['MEMORY DIGEST',data.memory_digest],['AUTHORITY TRANSFER',data.authority],['CREDENTIALS',data.credentials],['ENCRYPTION',data.encryption.status]].forEach(([label,value])=>{const term=document.createElement('dt'),detail=document.createElement('dd');term.textContent=label;detail.textContent=typeof value==='object'?JSON.stringify(value):String(value);facts.append(term,detail)})}
action('refreshStorage',loadStorage);
action('exportSnapshot',async()=>{const destination=$('exportDestination').value;const receipt=await api('/api/storage/export','POST',{destination});output('storageOut',receipt);$('snapshotBundle').value=destination;$('snapshotHash').value=receipt.manifest_sha256;notify('Continuity Capsule exported. Save its manifest hash separately.');await loadStorage();if(demo?.step===5){demo.step=6;demo.receipt='Export receipt / SHA-256 '+receipt.manifest_sha256;renderDemo()}});
function snapshotFields(){return {bundle:$('snapshotBundle').value,manifest_sha256:$('snapshotHash').value.trim()}}
action('verifySnapshot',async()=>{output('storageOut',await api('/api/storage/verify','POST',snapshotFields()));notify('Snapshot verification passed against the supplied manifest hash.')});
action('importSnapshot',async()=>{if(!confirm('Verify and restore into the new destination directory? The active runtime will not switch.'))return;output('storageOut',await api('/api/storage/import','POST',{...snapshotFields(),destination:$('importDestination').value}));notify('Snapshot restored to the new directory. Authority and credentials were not transferred.')});
const demoSteps=[
 ['Tell the current brain something.','This guide uses the deterministic reference fixture. Send the sample sentence as ordinary chat; it becomes durable memory.','PREPARE THE FIRST MESSAGE'],
 ['See what was stored.','Open Memory Vault and inspect the real record, its lifetime and its text hash.','INSPECT MEMORY VAULT'],
 ['Clock in another reference brain.','Review Brain Bay, then choose CLOCK IN BRAIN. A different identity must preserve the substrate and reset all grants.','PREPARE BRAIN B'],
 ['Ask the new brain about your story.','Send the prepared question. The fixture echoes delivered context; it does not establish model understanding or recall quality.','PREPARE THE FOLLOW-UP'],
 ['Inspect the actual delivery.','Open Synapse Trace. The guide checks that your earlier record ID appears in a routing receipt.','OPEN SYSTEM TRACE'],
 ['Export your continuity.','Choose a new local destination in Storage, then EXPORT SNAPSHOT. No destination is chosen for you.','OPEN STORAGE'],
 ['Continuity, with a receipt.','The real reference flow is complete. Keep the manifest hash separately. Authority and credentials do not travel. You can now verify the capsule or restore into a new directory.','INSPECT THE CAPSULE']
];
function renderDemo(){if(!demo)return;const step=demoSteps[demo.step];$('guidedDemo').classList.remove('hidden');$('demoProgress').textContent=demo.step===6?'REFERENCE DEMO / COMPLETED':'REFERENCE DEMO / '+(demo.step+1)+' OF 6';$('demoTitle').textContent=step[0];$('demoCopy').textContent=step[1];$('demoNext').textContent=step[2];$('demoReceipt').textContent=demo.receipt||''}
action('demoStart',async()=>{await loadOrbit();if(activeProfile.kind!=='reference'){await show('bay');throw new Error('Choose and clock in the reference fixture before starting the guided demo. Your current provider has been preserved.')}demo={step:0,systemId:orbit.runtime.system_id,firstBrain:activeProfile.model,memoryId:null,receipt:''};renderDemo();await demoNavigate()});
$('demoClose').onclick=()=>{demo=null;$('guidedDemo').classList.add('hidden')};
$('demoNext').onclick=async()=>{try{await demoNavigate()}catch(e){notify(e.message,true)}};
async function demoNavigate(){
 if(!demo)return;
 if(demo.step===0){await show('brain');$('chatText').value='My observatory project is Sunflower. Its first milestone is a lunar atlas.';$('chatText').focus()}
 else if(demo.step===1){await show('memory');if(memoryRecords.some(record=>record.id===demo.memoryId)){demo.step=2;demo.receipt='Durable record #'+demo.memoryId+' verified in Memory Vault.';renderDemo()}}
 else if(demo.step===2){await show('bay');hydrateProfile({kind:'reference',model:demo.firstBrain==='Reference Brain B'?'Reference Brain A':'Reference Brain B',base_url:'',allow_remote:false});updateProviderCards();$('saveProvider').focus()}
 else if(demo.step===3){await show('brain');$('chatText').value='What is the first milestone of my Sunflower observatory project?';$('chatText').focus()}
 else if(demo.step===4)await show('trace');else await show('settings');
}
async function demoChat(result,text){
 if(!demo)return;if(result.runtime.system_id!==demo.systemId)throw new Error('The guide substrate changed. Start a new guide for this substrate.');
 if(demo.step===0&&result.response_persistent){const records=(await api('/api/memory')).records,record=records.find(item=>item.kind==='user_turn'&&item.text===text);if(record){demo.memoryId=record.id;demo.step=1;demo.receipt='Turn committed / checkpoint '+result.result.checkpoint.sequence;renderDemo()}}
 else if(demo.step===3){if(!result.result.routing.memory_ids.includes(demo.memoryId))throw new Error('The prior record was not selected by routing. Inspect the trace before claiming delivery.');demo.step=4;demo.receipt='Prior memory #'+demo.memoryId+' delivered to '+result.provider.model+'.';renderDemo()}
}
window.addEventListener('pagehide',()=>{localStopCamera();localStopMic();window.speechSynthesis?.cancel()});
loadOrbit().then(loadContexts).catch(e=>{$('runtimePill').textContent='RUNTIME UNAVAILABLE';notify(e.message,true)});
setInterval(()=>{if(!document.hidden)loadOrbit().catch(()=>{localStopCamera();localStopMic();$('runtimePill').textContent='RUNTIME UNAVAILABLE'})},5000);
</script></body></html>'''
