"""Cosmic Fruit Fly: isolated, deterministic, fail-closed experiment harness.

Only the referenced Beast Box dyn12 function is imported from the parent project.
The discrete-time neuron network, environment, policy and plasticity are
computational assumptions, not measured Drosophila physiology.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
import math
import random
import statistics
import sys
import time
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THIS = Path(__file__).resolve().parent
ARMS = ('baseline', 'connectome', 'topology_control', 'memory_off', 'plasticity_off', 'lesion',
        'baseline_memory_off', 'topology_memory_off', 'lesion_memory_off')
SEEDS = tuple(range(8))


def canonical_dyn12(state: list[float], drive: list[float], step: int) -> list[float]:
    """Import the checked-in public Beast Box function, never a fallback copy."""
    path = ROOT / 'beastbox' / 'dyn12.py'
    if not path.is_file():
        raise FileNotFoundError(f'canonical dyn12 not found: {path}')
    spec = importlib.util.spec_from_file_location('fruitfly_canonical_dyn12', path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.update_dyn12(state, drive, step=step)


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def dump(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True, allow_nan=False) + '\n', encoding='utf-8')


@dataclass(frozen=True)
class Graph:
    ids: tuple[str, ...]
    edges: tuple[tuple[int, int, float], ...]
    dataset: dict


def fixture(path: Path, seed: int = 21) -> dict:
    """SYNTHETIC connectivity generated solely for engineering acceptance tests."""
    path.parent.mkdir(parents=True, exist_ok=True)
    r = random.Random(seed)
    with path.open('w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(('pre_root_id', 'post_root_id', 'syn_count', 'nt_type'))
        for src in range(24):
            for j in range(4):
                dst = (src + 1 + j * 5 + r.randrange(4)) % 24
                if dst == src:
                    dst = (dst + 1) % 24
                w.writerow((f'synthetic_{src:03}', f'synthetic_{dst:03}', r.randrange(2, 9), 'gaba' if src % 5 == 0 else 'ach'))
    meta = {
        'dataset': 'SYNTHETIC ENGINEERING FIXTURE — NOT FLY DATA',
        'version': f'fixture_v1_seed_{seed}',
        'source_url': 'locally generated by fixture() in harness.py',
        'license': 'generated-test-data; no biological provenance',
        'sha256': digest(path),
        'origin_class': 'synthetic',
    }
    dump(path.with_suffix('.metadata.json'), meta)
    return meta


def load_graph(path: Path, metadata: Path, max_edges: int = 1024, max_neurons: int = 64) -> Graph:
    """Strict input validation; bounded FIRST-ROW subset is disclosed and biased.

    A source-provided provenance declaration and exact-byte SHA are required.
    The claim that a file is biological is NOT independently authenticated here.
    """
    if max_edges < 1 or max_neurons < 2:
        raise ValueError('invalid resource bound')
    if not path.is_file() or not metadata.is_file():
        raise FileNotFoundError('connectivity CSV and provenance JSON are both required')
    meta = json.loads(metadata.read_text(encoding='utf-8'))
    for key in ('dataset', 'version', 'source_url', 'license', 'sha256', 'origin_class'):
        if not isinstance(meta.get(key), str) or not meta[key].strip():
            raise ValueError(f'missing provenance field: {key}')
    if meta['origin_class'] not in ('synthetic', 'source_declared_biological'):
        raise ValueError('unrecognized origin classification')
    if digest(path) != meta['sha256']:
        raise ValueError('source SHA-256 mismatch; fail closed')
    raw: list[tuple[str, str, int, str]] = []
    seen: set[str] = set()
    scanned = 0
    with path.open(newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        required = {'pre_root_id', 'post_root_id', 'syn_count'}
        if not required.issubset(set(reader.fieldnames or [])):
            raise ValueError('required FlyWire-compatible edge columns missing')
        for row in reader:
            scanned += 1
            if len(raw) >= max_edges:
                break
            a, b = row['pre_root_id'].strip(), row['post_root_id'].strip()
            if not a or not b:
                raise ValueError(f'missing neuron id at record {scanned}')
            try:
                weight = int(row['syn_count'])
            except (TypeError, ValueError) as e:
                raise ValueError(f'invalid synapse count at record {scanned}') from e
            if weight <= 0:
                raise ValueError('synapse counts must be positive integers')
            if a not in seen and len(seen) >= max_neurons:
                continue
            if b not in seen and len(seen) >= max_neurons:
                continue
            seen.update((a, b))
            raw.append((a, b, weight, (row.get('nt_type') or '').lower()))
    if len(seen) < 4 or len(raw) < 8:
        raise ValueError('too little connectivity for bounded experiment')
    ids = tuple(sorted(seen))
    lookup = {nid: n for n, nid in enumerate(ids)}
    aggregated: dict[tuple[int, int], float] = {}
    for a, b, w, nt in raw:
        # Assumption: sign only for explicit GABA annotation; other transmitters
        # retain positive count proxy, NOT an inference of physiological polarity.
        sgn = -1.0 if nt == 'gaba' else 1.0
        k = (lookup[a], lookup[b])
        aggregated[k] = aggregated.get(k, 0.0) + w * sgn
    edges = tuple((a, b, w) for (a, b), w in sorted(aggregated.items()) if w)
    extra = dict(meta)
    extra.update({'loaded_neurons': len(ids), 'loaded_edges': len(edges),
                  'first_rows_selected': len(raw), 'selection': 'file-order bounded first rows; not a representative sample',
                  'model_sign_rule': 'gaba negative; all other annotated/unannotated positive proxy'})
    return Graph(ids, edges, extra)


def rewired(graph: Graph, seed: int) -> Graph:
    """Preserves signed weight multiset and exact edge count; permutes target map."""
    rng = random.Random(seed + 90001)
    targets = [b for _, b, _ in graph.edges]
    rng.shuffle(targets)
    return Graph(graph.ids, tuple((a, targets[i], w) for i, (a, _, w) in enumerate(graph.edges)), graph.dataset)


def dynamics(graph: Graph, kind: str, neural: list[float], cue: float, ctx: float,
             plastic: list[float], lesion_set: frozenset[int]) -> tuple[list[float], int]:
    """Synchronous bounded leak + tanh; proxy synapse weights, not neural biophysics."""
    n = len(graph.ids)
    drive = [0.0] * n
    if kind != 'baseline':
        for i, (a, b, w) in enumerate(graph.edges):
            if a not in lesion_set and b not in lesion_set:
                drive[b] += 0.035 * w / 10.0 * (1.0 + plastic[i]) * neural[a]
    output = []
    for i in range(n):
        if i in lesion_set:
            output.append(0.0)
        else:
            inp = (0.55 * cue if i % 4 == 0 else 0.0) + (0.22 * ctx if i % 4 == 1 else 0.0)
            output.append(math.tanh(0.77 * neural[i] + inp + drive[i]))
    return output, len(graph.edges) if kind != 'baseline' else 0


def episode_plan(seed: int, ntrain: int, ntest: int) -> list[dict]:
    """Matched private environment schedule; test uses withheld noisier delay."""
    rng = random.Random(781 + seed)
    rows = []
    for i in range(ntrain + ntest):
        cue = rng.choice((-1.0, 1.0))
        ctx = rng.choice((-1.0, 1.0))
        rows.append({'cue': cue, 'context': ctx, 'target': int(cue * ctx > 0),
                     'delay': 4 if i < ntrain else 7,
                     'distractors': [rng.uniform(-0.23, 0.23) for _ in range(7)],
                     'phase': 'train' if i < ntrain else 'test'})
    return rows


def run_arm(graph: Graph, arm: str, seed: int, ntrain: int = 80, ntest: int = 40) -> dict:
    if arm not in ARMS:
        raise ValueError('unknown arm')
    rng = random.Random(seed + 20200)
    g = rewired(graph, seed) if arm.startswith('topology_') else graph
    network_kind = 'baseline' if arm.startswith('baseline') else 'connectome'
    memory_enabled = 'memory_off' not in arm
    plasticity_enabled = arm != 'plasticity_off'
    n = len(g.ids)
    weights = [0.0] * 26  # 12 canonical state + 12 neural pooling + cue/context + bias
    memory: dict[tuple[int, int], tuple[int, int]] = {}
    plastic = [0.0] * len(g.edges)
    lesion_set = frozenset(rng.sample(range(n), max(1, n // 4))) if arm.startswith('lesion') else frozenset()
    correct: dict[str, int] = {'train': 0, 'test': 0}
    total: dict[str, int] = {'train': 0, 'test': 0}
    neural_step_ops = 0
    state_norms: list[float] = []
    prediction_log: list[dict] = []
    start_ns = time.perf_counter_ns()
    steps = 0
    for e, trial in enumerate(episode_plan(seed, ntrain, ntest)):
        neural = [0.0] * n
        state = [0.0] * 12
        # Sensor event -> network -> canonical dyn12 -> bounded retrieval ->
        # policy action -> environment reward -> optional plasticity.
        for t in range(trial['delay'] + 1):
            cue = trial['cue'] if t == 0 else trial['distractors'][t - 1]
            ctx = trial['context'] if t == trial['delay'] else 0.0
            neural, ops = dynamics(g, network_kind, neural, cue, ctx, plastic, lesion_set)
            neural_step_ops += ops
            pool = [0.0] * 12
            counts = [0] * 12
            for i, x in enumerate(neural):
                pool[i % 12] += x
                counts[i % 12] += 1
            pool = [v / max(1, counts[j]) for j, v in enumerate(pool)]
            state = canonical_dyn12(state, pool, step=steps)
            steps += 1
        key = (int(trial['cue']), int(trial['context']))
        features = state + pool + [trial['context'], 1.0]
        assert len(features) == 26
        score = sum(w * x for w, x in zip(weights, features))
        # Memory is a bounded independent lookup, not a model weight or tool capability.
        if memory_enabled and key in memory:
            previous, visits = memory[key]
            if visits >= 2:
                score += 0.3 * (2 * previous - 1)
        prediction = int(score >= 0)
        reward = int(prediction == trial['target'])
        phase = trial['phase']
        total[phase] += 1
        correct[phase] += reward
        state_norms.append(math.sqrt(sum(x * x for x in state)))
        prediction_log.append({'episode': e, 'phase': phase, 'target': trial['target'],
                               'action': prediction, 'reward': reward, 'state_norm': round(state_norms[-1], 8)})
        if phase == 'train':
            if memory_enabled:
                memory[key] = (trial['target'], memory.get(key, (0, 0))[1] + 1)
            if plasticity_enabled:
                err = trial['target'] - prediction
                for j, x in enumerate(features):
                    weights[j] = max(-2.0, min(2.0, weights[j] + 0.1 * err * x))
                if network_kind != 'baseline':
                    for j, (a, b, _) in enumerate(g.edges):
                        # Bounded, reward-modulated computational Hebbian proxy.
                        plastic[j] = max(-0.2, min(0.2, 0.995 * plastic[j] + 0.001 * (2 * reward - 1) * neural[a] * neural[b]))
    elapsed = (time.perf_counter_ns() - start_ns) / 1e6
    return {'arm': arm, 'seed': seed, 'train_accuracy': correct['train'] / total['train'],
            'test_accuracy': correct['test'] / total['test'],
            'correct': correct, 'total': total, 'test_errors': total['test'] - correct['test'],
            'state_norm_mean': statistics.mean(state_norms), 'state_norm_sd': statistics.pstdev(state_norms),
            'memory_entries': len(memory), 'plasticity_l1': sum(abs(v) for v in plastic),
            'neural_edge_ops': neural_step_ops, 'steps': steps, 'elapsed_ms': elapsed,
            'lesion_neurons': len(lesion_set), 'parameters': len(weights) + len(plastic),
            'trace': prediction_log}


def experiment(graph: Graph, seeds: tuple[int, ...] = SEEDS, ntrain: int = 80, ntest: int = 40) -> dict:
    runs = [run_arm(graph, arm, seed, ntrain, ntest) for seed in seeds for arm in ARMS]
    summary = {}
    for arm in ARMS:
        selected = [r for r in runs if r['arm'] == arm]
        summary[arm] = {
            'test_accuracy_mean': statistics.mean(r['test_accuracy'] for r in selected),
            'test_accuracy_sd': statistics.pstdev(r['test_accuracy'] for r in selected),
            'train_accuracy_mean': statistics.mean(r['train_accuracy'] for r in selected),
            'test_errors_total': sum(r['test_errors'] for r in selected),
            'memory_entries_mean': statistics.mean(r['memory_entries'] for r in selected),
            'edge_ops_mean': statistics.mean(r['neural_edge_ops'] for r in selected),
            'elapsed_ms_mean': statistics.mean(r['elapsed_ms'] for r in selected),
        }
    return {'classification': 'synthetic_engineering_only' if graph.dataset['origin_class'] == 'synthetic'
            else 'source_declared_biological_candidate_requires_independent_provenance_review',
            'graph': graph.dataset, 'settings': {'seeds': list(seeds), 'train': ntrain, 'test': ntest,
            'arms': list(ARMS), 'model_provider': 'none; deterministic software policy',
            'external_authority': 'none; sandbox actions only'},
            'summary': summary, 'runs': runs}


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument('--csv', type=Path)
    p.add_argument('--metadata', type=Path)
    p.add_argument('--output', type=Path, default=THIS / 'evidence' / 'latest')
    p.add_argument('--fixture', action='store_true', help='generate and execute SYNTHETIC fixture only')
    p.add_argument('--max-edges', type=int, default=1024)
    p.add_argument('--max-neurons', type=int, default=64)
    p.add_argument('--seeds', type=int, default=8)
    p.add_argument('--train', type=int, default=80)
    p.add_argument('--test', type=int, default=40)
    a = p.parse_args()
    if a.seeds < 1 or a.train < 1 or a.test < 1:
        p.error('positive seeds/train/test required')
    if a.fixture:
        if a.csv or a.metadata:
            p.error('--fixture cannot be combined with external source')
        a.csv = a.output / 'synthetic_connections.csv'
        a.metadata = a.csv.with_suffix('.metadata.json')
        fixture(a.csv)
    if not a.csv or not a.metadata:
        p.error('real CSV and metadata both required; no implicit synthetic fallback')
    graph = load_graph(a.csv, a.metadata, max_edges=a.max_edges, max_neurons=a.max_neurons)
    result = experiment(graph, tuple(range(a.seeds)), a.train, a.test)
    a.output.mkdir(parents=True, exist_ok=True)
    with (a.output / 'trials.jsonl').open('w', encoding='utf-8') as f:
        for run in result.pop('runs'):
            f.write(json.dumps(run, sort_keys=True, allow_nan=False) + '\n')
    result['input_sha256'] = digest(a.csv)
    result['canonical_dyn12_sha256'] = digest(ROOT / 'beastbox' / 'dyn12.py')
    result['harness_sha256'] = digest(Path(__file__))
    dump(a.output / 'summary.json', result)
    sums = {p.name: digest(p) for p in sorted(a.output.iterdir()) if p.is_file()}
    dump(a.output / 'SHA256SUMS.json', sums)
    print(json.dumps({'classification': result['classification'], 'summary': result['summary'],
                      'input_sha256': result['input_sha256']}, indent=2, sort_keys=True))


if __name__ == '__main__':
    main()
