#!/usr/bin/env python3
"""Offline preregistered Quantum Buddy Phase-8 runner; no cloud or hardware path.

--smoke is a synthetic harness test, not RAWRPHOS inference evidence.
Real 14K inference requires an explicitly pinned checkpoint and owner-enabled
local CPU run. This script never loads live bio data, Cosmos or provider SDKs.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from beastbox.quantum_buddy.operators import QuantumStateOperator
from beastbox.quantum_buddy.shadow import (
    FrozenPhase8Config,
    generate_synthetic_cohort,
    run_phase8,
)


def _fixture_runner(prompt, seed, dyn12, qstate12, mode):
    """Transparent deterministic fake; never present this as model results."""
    canonical = json.dumps(
        [prompt, seed, dyn12, qstate12, mode],
        sort_keys=True, separators=(",", ":"), allow_nan=False,
    )
    token = int.from_bytes(hashlib.sha256(canonical.encode()).digest()[:4], "big")
    baseline = "This response is generated by a deterministic smoke-test fixture."
    response = baseline if mode == "off" else f"Smoke-test fixture variant {token % 11}."
    return {
        "logit_l2": 0.0 if mode == "off" else (token % 1001) / 10_000,
        "response_ordinary": baseline,
        "response_buddy": response,
        "duration_ms": 1.0 + (token % 100)/100,
        "checkpoint_sha256": "0"*64,
        "model_weights_changed": False,
        "performance_gain_proven": False,
        "fresh_hardware_used": False,
        "quantum_advantage_proven": False,
    }


def _load_native_runner(path: str, expected_sha: str):
    if (not isinstance(expected_sha, str) or len(expected_sha) != 64
            or any(ch not in "0123456789abcdef" for ch in expected_sha)):
        raise ValueError("expected SHA-256 must pin a real checkpoint")
    sys.path.insert(0, str(ROOT/"models"))
    from rawrphos.inference.engine import Engine
    engine = Engine(path, max_new_tokens=32, threads=4,
                    expected_sha256=expected_sha, device="cpu")
    actual = engine.metadata["checkpoint_sha256"]
    if actual != expected_sha:
        raise ValueError("loaded checkpoint SHA differs from pinned expected SHA")

    def real_runner(prompt, seed, dyn12, qstate12, mode):
        result = engine.shadow_condition(
            prompt,
            list(dyn12),
            list(qstate12),
            max_tokens=24,
            seed=seed,
        )
        if result["checkpoint_sha256"] != actual:
            raise ValueError("checkpoint changed during Phase 8")
        return result

    return real_runner


def _sha_text(contents):
    return hashlib.sha256(contents).hexdigest()


def _write_evidence(folder: Path, report: dict, prereg: dict):
    folder.mkdir(parents=True, exist_ok=True)
    report_text = json.dumps(
        report, sort_keys=True, indent=2, ensure_ascii=True, allow_nan=False,
    ) + "\n"
    report_file = folder/"report.json"
    manifest_file = folder/"run-manifest.json"
    report_file.write_text(report_text, encoding="utf-8")
    manifest_text = json.dumps({
        "schema": "quantum-buddy-phase8-evidence-v1",
        "prereg_sha256": report["prereg_sha256"],
        "report_sha256": _sha_text(report_text.encode()),
        "measurement_class": report["measurement_class"],
        "fresh_hardware_used": False,
        "cosmos_live_write_tested": False,
        "production_deployed": False,
        "simulator_kind": "deterministic-ideal-six-qubit-statevector",
        "full_preregistration_evaluated": report["full_preregistration_evaluated"],
    }, sort_keys=True, indent=2) + "\n"
    manifest_file.write_text(manifest_text, encoding="utf-8")
    sums = [
        f"{_sha_text(report_text.encode())}  report.json",
        f"{_sha_text(manifest_text.encode())}  run-manifest.json",
    ]
    (folder/"SHA256SUMS").write_text("\n".join(sums)+"\n", encoding="utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Offline Quantum Buddy Phase-8 frozen shadow controls"
    )
    parser.add_argument("--smoke", action="store_true",
                        help="synthetic fake-model harness only; no model evidence")
    parser.add_argument("--checkpoint", type=str,
                        help="required actual local native checkpoint directory for full run")
    parser.add_argument("--expected-sha256", type=str,
                        help="required immutable checkpoint weight SHA-256")
    parser.add_argument("--confirm-cpu-intensive", action="store_true",
                        help="explicitly authorize a long frozen CPU inference sweep")
    parser.add_argument(
        "--output", type=Path,
        default=ROOT/"experiments/quantum-buddy-phase8/results",
    )
    args = parser.parse_args(argv)
    if args.smoke:
        if args.checkpoint or args.expected_sha256 or args.confirm_cpu_intensive:
            parser.error("smoke fixture and native checkpoint settings cannot be mixed")
        model_runner = _fixture_runner
        checkpoint_sha = "0"*64
        measurement_class = "SYNTHETIC_MODEL_FIXTURE"
    else:
        if not args.checkpoint or not args.expected_sha256:
            parser.error("real Phase-8 run requires --checkpoint and --expected-sha256")
        if not args.confirm_cpu_intensive:
            parser.error("full Phase-8 requires --confirm-cpu-intensive")
        model_runner = _load_native_runner(args.checkpoint, args.expected_sha256)
        checkpoint_sha = args.expected_sha256
        measurement_class = "FROZEN_NATIVE_CPU_INFERENCE"

    prereg_path = ROOT/"experiments/quantum-buddy-phase8/preregistration.json"
    prereg = json.loads(prereg_path.read_text(encoding="utf-8"))
    config = FrozenPhase8Config.from_dict(
        prereg, model_checkpoint_sha256=checkpoint_sha,
    )
    cohort = generate_synthetic_cohort(
        config.prereg["cohort_size"],
        config.prereg["drifts_per_person"],
        seed=config.prereg["cohort_seed"],
    )
    # Replay is a fixed *control*, not a person-parameterized identity.
    operator = QuantumStateOperator(replay_bank={
        "phase8-calibration": [0.1,-0.2]*6,
    })
    full = not args.smoke
    prompts = prereg["prompt_bank"] if full else prereg["prompt_bank"][:2]
    seeds = prereg["sampling_seeds"] if full else prereg["sampling_seeds"][:2]
    report = run_phase8(
        cohort, prompts, seeds, operator, model_runner, config,
    )
    report["measurement_class"] = measurement_class
    report["native_model_inference_attested"] = full
    report["full_preregistration_evaluated"] = full
    report["hardware_promotion_approved"] = False
    report["task_quality_verified"] = False
    _write_evidence(args.output, report, prereg)
    print(json.dumps({
        "report": str(args.output/"report.json"),
        "measurement_class": measurement_class,
        "native_model_inference_attested": full,
        "fresh_hardware_used": False,
        "hardware_promotion_approved": False,
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
